import crypto from 'node:crypto';
import { canonicalJson, sha256 } from './config.mjs';

export const FEDERATION_SCHEMA = 'celestan-execution-federation-v1';
export const FEDERATION_STATES = Object.freeze(['ready', 'claimed', 'running', 'deferred', 'handoff', 'finalized', 'failed']);
export const CoordinationUnavailableError = class extends Error {
  constructor(message = 'execution coordination is unavailable') { super(message); this.name = 'CoordinationUnavailableError'; this.category = 'coordination-unavailable'; }
};
const conflict = (message) => Object.assign(new Error(message), { category: 'conflict' });
const required = (value, field, max = 500) => { if (typeof value !== 'string' || !value.trim() || value.length > max || /[\0\r\n]/.test(value)) throw new Error(`${field} must be a bounded safe string`); return value; };
const isSecretKey = (key) => /(?:apikey|token|secret|password|passwd|credential|authorization|privatekey|accesskey)/i.test(String(key).replace(/[_-]/g, ''));
const json = (value) => value == null ? null : JSON.parse(JSON.stringify(value));
const id = (prefix) => `${prefix}-${crypto.randomUUID()}`;
const row = (result) => result.rows[0];
const stamp = (v) => v?.toISOString?.() || v;

export function normalizeObserverLineage(input = {}) {
  return { schema: 'celestan-observer-lineage-v1', workOrderId: required(input.workOrderId, 'workOrderId'), executionId: required(input.executionId, 'executionId'), parentExecutionId: input.parentExecutionId || null, provider: required(input.provider || 'unavailable', 'provider', 160), mode: input.mode === 'foreground' ? 'foreground' : 'background', handoffId: input.handoffId || null, checkpointDigest: input.checkpoint == null ? null : sha256(input.checkpoint) };
}
export function redactFederation(value, secrets = []) {
  const replacements = secrets.filter((s) => typeof s === 'string' && s.length >= 4);
  const walk = (v) => typeof v === 'string' ? replacements.reduce((out, secret) => out.split(secret).join('[REDACTED]'), v) : Array.isArray(v) ? v.map(walk) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, isSecretKey(k) ? '[REDACTED]' : walk(x)])) : v;
  return walk(json(value));
}

export function assertCoordination(adapter) {
  if (!adapter || adapter.available === false) throw new CoordinationUnavailableError();
  for (const method of ['createWorkOrder', 'claim', 'checkpoint', 'finalize', 'reconstruct']) if (typeof adapter[method] !== 'function') throw new Error(`federation adapter missing ${method}`);
  return adapter;
}

export class PostgresFederationAdapter {
  constructor({ pool, now = () => new Date() } = {}) { if (!pool) throw new Error('Postgres pool is required'); this.pool = pool; this.now = now; this.available = true; }
  async tx(fn) { const client = await this.pool.connect(); try { await client.query('BEGIN'); const out = await fn(client); await client.query('COMMIT'); return out; } catch (e) { await client.query('ROLLBACK').catch(() => {}); throw e; } finally { client.release(); } }
  async createWorkOrder({ workOrderId, project, intent, repository = {} }) {
    workOrderId = required(workOrderId || id('work'), 'workOrderId'); project = required(project, 'project');
    intent = redactFederation(intent); repository = redactFederation(repository);
    return this.tx(async (c) => { const inserted = await c.query(`INSERT INTO federation_work_orders(work_order_id,project,intent,repository) VALUES ($1,$2,$3,$4) ON CONFLICT (work_order_id) DO NOTHING RETURNING *`, [workOrderId, project, intent, repository]); const current = row(inserted) || row(await c.query('SELECT * FROM federation_work_orders WHERE work_order_id=$1 FOR SHARE', [workOrderId])); if (canonicalJson({ project: current.project, intent: current.intent, repository: current.repository }) !== canonicalJson({ project, intent, repository })) throw conflict('work order identity'); return fromWork(current); });
  }
  async getWorkOrder(workOrderId) { const value = row(await this.pool.query('SELECT * FROM federation_work_orders WHERE work_order_id=$1', [required(workOrderId, 'workOrderId')])); return value && fromWork(value); }
  async claim({ workOrderId, executionId = id('exec'), provider, mode = 'background', owner = id('owner'), ttlMs = 300000, repository = {}, parentExecutionId = null }) {
    required(workOrderId, 'workOrderId'); required(provider, 'provider'); required(owner, 'owner'); if (!['foreground', 'background'].includes(mode)) throw new Error('execution mode is invalid');
    return this.tx(async (c) => this.claimInTransaction(c, workOrderId, { executionId, provider, mode, owner, ttlMs, repository, parentExecutionId, emitEvent: true }));
  }
  async renew(executionId, claim, ttlMs = 300000) { return this.tx(async (c) => { const current = await lockClaim(c, executionId, claim); const updated = row(await c.query(`UPDATE federation_executions SET lease_until=clock_timestamp()+($1::bigint * interval '1 millisecond'),updated_at=clock_timestamp() WHERE execution_id=$2 RETURNING *`, [ttlMs, executionId])); return fromExecution(updated); }); }
  async release(executionId, claim) { return this.tx(async (c) => { const current = await lockClaim(c, executionId, claim); const updated = row(await c.query(`UPDATE federation_executions SET state=CASE WHEN state IN ('claimed','running') THEN 'deferred' ELSE state END,lease_until=NULL,updated_at=clock_timestamp() WHERE execution_id=$1 RETURNING *`, [executionId])); await event(c, current.work_order_id, executionId, 'released', {}); return fromExecution(updated); }); }
  async defer(executionId, claim) { return this.release(executionId, claim); }
  async checkpoint(executionId, checkpoint, claim) { return this.tx(async (c) => { const current = await lockClaim(c, executionId, claim); const safeCheckpoint = redactFederation(checkpoint); const updated = row(await c.query(`UPDATE federation_executions SET state='running',checkpoint=$1,updated_at=clock_timestamp() WHERE execution_id=$2 RETURNING *`, [safeCheckpoint, executionId])); await event(c, current.work_order_id, executionId, 'checkpointed', { digest: sha256(safeCheckpoint) }); return fromExecution(updated); }); }
  async handoff(executionId, { provider, mode = 'background', owner = id('owner'), ttlMs = 300000, reason = 'continuation', handoffId = id('handoff') } = {}, claim) { required(handoffId, 'handoffId'); required(reason, 'reason'); return this.tx(async (c) => { await c.query('SELECT * FROM federation_work_orders WHERE work_order_id=(SELECT work_order_id FROM federation_executions WHERE execution_id=$1) FOR UPDATE', [executionId]); const prior = row(await c.query('SELECT to_execution_id FROM federation_handoffs WHERE handoff_id=$1 AND from_execution_id=$2', [handoffId, executionId])); if (prior) { const next = row(await c.query('SELECT * FROM federation_executions WHERE execution_id=$1', [prior.to_execution_id])); if (!next) throw new Error('handoff target not found'); return fromExecution(next); } const current = await lockClaim(c, executionId, claim); await c.query(`UPDATE federation_executions SET state='handoff',lease_until=NULL,updated_at=clock_timestamp() WHERE execution_id=$1`, [executionId]); const next = await this.claimInTransaction(c, current.work_order_id, { provider, mode, owner, ttlMs, parentExecutionId: executionId }); await c.query(`INSERT INTO federation_handoffs(handoff_id,work_order_id,from_execution_id,to_execution_id,checkpoint,reason) VALUES ($1,$2,$3,$4,$5,$6)`, [handoffId, current.work_order_id, executionId, next.id, redactFederation(current.checkpoint), redactFederation(reason)]); return next; }); }
  async continue(executionId, options, claim) { return this.handoff(executionId, options, claim); }
  async finalize(executionId, value, claim) { return this.tx(async (c) => { const current = await lockClaim(c, executionId, claim); const safeCheckpoint = redactFederation(value.checkpoint ?? current.checkpoint, value.secrets || []); const updated = row(await c.query(`UPDATE federation_executions SET state=$1,checkpoint=$2,lease_until=NULL,updated_at=clock_timestamp() WHERE execution_id=$3 RETURNING *`, [value.status === 'failed' ? 'failed' : 'finalized', safeCheckpoint, executionId])); await event(c, current.work_order_id, executionId, 'finalized', redactFederation(value, value.secrets || [])); return fromExecution(updated); }); }
  async reconstruct(workOrderId) { const order = row(await this.pool.query('SELECT * FROM federation_work_orders WHERE work_order_id=$1', [workOrderId])); if (!order) return null; const executions = (await this.pool.query('SELECT * FROM federation_executions WHERE work_order_id=$1 ORDER BY created_at,execution_id', [workOrderId])).rows.map(fromExecution); const handoffs = (await this.pool.query('SELECT * FROM federation_handoffs WHERE work_order_id=$1 ORDER BY created_at,handoff_id', [workOrderId])).rows.map((x) => ({ id: x.handoff_id, fromExecutionId: x.from_execution_id, toExecutionId: x.to_execution_id, checkpoint: x.checkpoint, reason: x.reason, createdAt: stamp(x.created_at) })); return { schema: FEDERATION_SCHEMA, workOrder: fromWork(order), executions, handoffs }; }
  async repositoryDrift(workOrderId, repository) { const order = await this.getWorkOrder(workOrderId); if (!order) throw new Error('work order not found'); return { drifted: canonicalJson(order.repository) !== canonicalJson(repository), expected: order.repository, actual: repository }; }
}

async function lockClaim(c, executionId, claim) { const current = row(await c.query('SELECT * FROM federation_executions WHERE execution_id=$1 AND claim_owner=$2 AND claim_fence=$3 AND lease_until>clock_timestamp() FOR UPDATE', [executionId, claim?.owner, String(claim?.fence)])); if (!current) throw Object.assign(new Error('lost federation fencing ownership'), { category: 'ownership-lost' }); return current; }
PostgresFederationAdapter.prototype.claimInTransaction = async function(c, workOrderId, input) { const order = row(await c.query('SELECT * FROM federation_work_orders WHERE work_order_id=$1 FOR UPDATE', [workOrderId])); if (!order) throw new Error('work order not found'); const active = row(await c.query(`SELECT * FROM federation_executions WHERE work_order_id=$1 AND state IN ('claimed','running') AND lease_until>clock_timestamp() ORDER BY created_at DESC`, [workOrderId])); if (active) throw conflict('overlapping active mutation claim'); const counter = row(await c.query('UPDATE federation_work_orders SET next_claim_fence=next_claim_fence+1,updated_at=clock_timestamp() WHERE work_order_id=$1 RETURNING next_claim_fence', [workOrderId])); const executionId = input.executionId || id('exec'); const fence = BigInt(counter.next_claim_fence); const value = row(await c.query(`INSERT INTO federation_executions(execution_id,work_order_id,provider,mode,state,claim_owner,claim_fence,lease_until,repository,lineage) VALUES ($1,$2,$3,$4,'claimed',$5,$6,clock_timestamp()+($7::bigint * interval '1 millisecond'),$8,$9) RETURNING *`, [executionId, workOrderId, input.provider, input.mode, input.owner, String(fence), input.ttlMs, redactFederation(input.repository || {}), normalizeObserverLineage({ workOrderId, executionId, provider: input.provider, mode: input.mode, parentExecutionId: input.parentExecutionId })])); if (input.emitEvent) await event(c, workOrderId, executionId, 'claimed', redactFederation({ owner: input.owner, fence: String(fence), mode: input.mode })); return fromExecution(value); };
async function event(c, workOrderId, executionId, type, payload) { await c.query('INSERT INTO federation_events(event_id,work_order_id,execution_id,event_type,payload) VALUES ($1,$2,$3,$4,$5)', [id('event'), workOrderId, executionId, type, payload]); }
function fromWork(v) { return { id: v.work_order_id, project: v.project, intent: v.intent, repository: v.repository, state: v.state, version: String(v.version), createdAt: stamp(v.created_at), updatedAt: stamp(v.updated_at) }; }
function fromExecution(v) { return { schema: FEDERATION_SCHEMA, id: v.execution_id, workOrderId: v.work_order_id, provider: v.provider, mode: v.mode, state: v.state, claim: v.claim_owner ? { owner: v.claim_owner, fence: String(v.claim_fence), leaseUntil: stamp(v.lease_until) } : null, checkpoint: v.checkpoint, repository: v.repository, lineage: v.lineage, createdAt: stamp(v.created_at), updatedAt: stamp(v.updated_at) }; }
