import { appendFile, mkdir, mkdtemp, open, readFile, readdir, rename, rm, stat, unlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { hostTelemetry } from './host-telemetry.mjs';
import { validateModelPolicy } from './config.mjs';
import { createInferenceRecord, normalizeInferenceFailure } from './inference-management.mjs';
import { createSemanticEvidenceEnvelope, validateSemanticEvidence, validateSemanticEvidenceDraft } from './semantic-evidence.mjs';

export const WAKE_REASONS = Object.freeze(['scheduled', 'user', 'webhook', 'github', 'retry', 'self_scheduled', 'observer', 'maintenance']);
export const LEASE_TTL_MS = 300000;
export const HEARTBEAT_INTERVAL_MS = Math.floor(LEASE_TTL_MS / 3);
const RETRYABLE = new Set(['timeout', 'network', 'provider']);
const TERMINAL = new Set(['success', 'failed', 'cancelled', 'crashed']);
const INVOKABLE = new Set(['manifested', 'requeued', 'retrying']);
const RECOVERABLE = new Set([...INVOKABLE, 'running']);
const MAX_TEXT = 500, MAX_OUTPUT = 64 * 1024, MAX_EVIDENCE = 64 * 1024, MAX_RESULT = 64 * 1024, MAX_RECOVERY = 3;
const safeText = (v, field, max = MAX_TEXT) => { if (typeof v !== 'string' || !v.trim() || v.length > max || /[\0\r\n]/.test(v)) throw new Error(`${field} must be a bounded safe string`); return v; };
const id = (prefix = 'x') => `${prefix}-${Date.now().toString(36)}-${crypto.randomBytes(12).toString('hex')}`;
const digest = (data) => crypto.createHash('sha256').update(data).digest('hex');
const json = (v) => JSON.stringify(v, null, 2) + '\n';
const now = () => new Date().toISOString();
const exists = async (p) => { try { await stat(p); return true; } catch { return false; } };
const enc = (value) => encodeURIComponent(value);
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function observerTaskType(purpose) { const value = String(purpose).toLowerCase(); for (const type of ['implementation', 'debugging', 'review', 'verification', 'research', 'planning', 'architecture', 'documentation', 'operations', 'orchestration']) if (value.includes(type)) return type; return 'other'; }
async function enrichManifestTelemetry(store, manifest) { if (typeof store.inferenceRecords !== 'function') return manifest; const records = await store.inferenceRecords({ executionId: manifest.execution.id }); if (!records.length) return manifest; return { ...manifest, modelRuntimeTelemetry: { availability: 'available', invocations: records.map((r) => ({ invocationId: r.recordId, provider: r.route.provider, model: r.route.model, agent: r.identity.agent, role: r.identity.role, task: { type: observerTaskType(r.task.purpose), label: r.task.purpose }, startedAt: r.timing.startedAt, finishedAt: r.timing.finishedAt, durationMs: r.timing.latencyMs, retry: { attempt: r.retry.attempt, retryCount: r.retry.retries }, status: r.outcome, outcome: r.outcome })), failures: records.filter((r) => r.failure).map((r) => ({ failureId: `failure-${r.recordId}`, invocationId: r.recordId, category: r.failure.foundryCategory, errorClass: r.failure.class, timestamp: r.timing.finishedAt, retryable: r.failure.retryable, retryCount: r.retry.retries })), transitions: [] } }; }

export function validateWakeReason(reason) { if (!WAKE_REASONS.includes(reason)) throw new Error(`wake_reason must be one of: ${WAKE_REASONS.join(', ')}`); return reason; }
export function validateNextWake(value) {
  if (value === null || value === undefined) return null;
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('requested_next_wake must be an object or null');
  if (Object.keys(value).sort().join(',') !== 'priority,project,reason,time') throw new Error('requested_next_wake has unexpected fields');
  const time = safeText(value.time, 'requested_next_wake.time', 64); if (Number.isNaN(Date.parse(time))) throw new Error('requested_next_wake.time must be an ISO timestamp');
  return { time, reason: validateWakeReason(value.reason), priority: safeText(value.priority, 'requested_next_wake.priority', 32), project: safeText(value.project, 'requested_next_wake.project', 160) };
}

async function durableWrite(target, value, flag = 'w') {
  await mkdir(path.dirname(target), { recursive: true });
  const temp = `${target}.${process.pid}.${crypto.randomBytes(6).toString('hex')}.tmp`;
  const handle = await open(temp, flag === 'wx' ? 'wx' : 'w', 0o600);
  try { await handle.writeFile(json(value)); await handle.sync(); } finally { await handle.close(); }
  await rename(temp, target);
  let dir; try { dir = await open(path.dirname(target), 'r'); await dir.sync(); } catch { /* unsupported directory fsync */ } finally { await dir?.close().catch(() => {}); }
}

async function readBoundedJson(target, maximum) {
  const handle = await open(target, 'r');
  try { const info = await handle.stat(); if (info.size > maximum) throw Object.assign(new Error('bounded file exceeds hard limit'), { category: 'validation' }); return JSON.parse(await handle.readFile('utf8')); }
  finally { await handle.close(); }
}

export class Store {
  constructor(root, config = {}) { if (!root) throw new Error('store path is required'); this.config = config; this.root = path.resolve(root); this.manifests = path.join(this.root, 'manifests'); this.raw = path.join(this.root, 'raw'); this.leases = path.join(this.root, 'leases'); this.locks = path.join(this.root, 'locks'); this.results = path.join(this.root, 'results'); this.semanticEvidence = path.join(this.root, 'semantic-evidence'); }
  async init() { await Promise.all([mkdir(this.manifests, { recursive: true }), mkdir(this.raw, { recursive: true }), mkdir(this.leases, { recursive: true }), mkdir(this.locks, { recursive: true }), mkdir(this.results, { recursive: true }), mkdir(this.semanticEvidence, { recursive: true })]); }
  file(dir, name) { return path.join(dir, `${enc(name)}.json`); }
  async atomic(target, value) { return durableWrite(target, value); }
  async manifest(executionId) { return JSON.parse(await readFile(this.file(this.manifests, executionId), 'utf8')); }
  async manifestsAll() { await this.init(); return Promise.all((await readdir(this.manifests)).filter((x) => x.endsWith('.json')).sort().map((x) => readFile(path.join(this.manifests, x), 'utf8').then(JSON.parse).then((manifest) => enrichManifestTelemetry(this, manifest)))); }
  async append(kind, record) { await this.init(); const handle = await open(path.join(this.root, `${kind}.ndjson`), 'a', 0o600); try { await handle.writeFile(JSON.stringify(record) + '\n'); await handle.sync(); } finally { await handle.close(); } }
  async event(type, fields = {}) { await this.append('events', { schema: 'celestan-runtime-event-v1', id: id('evt'), at: now(), type: safeText(type, 'event type', 64), ...boundedFields(fields) }); }
  async telemetry(fields = {}) { await this.append('telemetry', { schema: 'celestan-runtime-telemetry-v1', id: id('tel'), at: now(), ...boundedFields(fields) }); }
  async inferenceRecord(record) { if (record?.schema !== 'celestan-runtime-inference-v1') throw new Error('normalized inference record is required'); await this.append('inference', record); return record; }
  async inferenceRecords({ executionId, workOrder, limit = 1000 } = {}) { await this.init(); if (!Number.isSafeInteger(limit) || limit < 1 || limit > 10000) throw new Error('inference record limit must be from 1 to 10000'); const target = path.join(this.root, 'inference.ndjson'); if (!(await exists(target))) return []; const handle = await open(target, 'r'); try { if ((await handle.stat()).size > 16 * 1024 * 1024) throw new Error('inference telemetry exceeds bounded read limit'); return (await handle.readFile('utf8')).split('\n').filter(Boolean).map(JSON.parse).filter((record) => (!executionId || record.logical?.executionId === executionId) && (!workOrder || record.logical?.workOrder === workOrder)).slice(-limit); } finally { await handle.close(); } }
  async lock(name, staleMs = LEASE_TTL_MS) {
    await this.init(); const target = path.join(this.locks, `${enc(name)}.lock`); const token = `${process.pid}-${crypto.randomBytes(12).toString('hex')}`; const deadline = Date.now() + Math.max(staleMs, 1000) * 2;
    for (;;) try { await writeFile(target, JSON.stringify({ token, at: Date.now() }), { flag: 'wx', mode: 0o600 }); return async () => { try { if ((await JSON.parse(await readFile(target, 'utf8'))).token === token) await unlink(target); } catch (e) { if (e.code !== 'ENOENT') throw e; } }; }
    catch (e) { if (!['EEXIST', 'EPERM', 'EBUSY'].includes(e.code)) throw e; try { const old = JSON.parse(await readFile(target, 'utf8')); if (Date.now() - old.at > staleMs) await unlink(target).catch(() => {}); else await wait(5); } catch (x) { if (Date.now() > deadline) throw new Error('lock contention exceeded bounded deadline'); if (x.code !== 'ENOENT') await wait(5); } }
  }
  async createManifest(input) {
    await this.init(); const executionId = input.executionId || id('run'); safeText(executionId, 'executionId', 180); const project = safeText(input.project, 'project', 160);
    validateModelPolicy(input.model, this.config);
    const topology = await this.validateAndLinkTopology(input.topology || { rootId: executionId, childIds: [] }, executionId);
    const manifest = { schema: 'celestan-runtime-manifest-v1', execution: { id: executionId, project, task: safeText(input.task, 'task', 2000), model: safeText(input.model, 'model', 300), agent: safeText(input.agent, 'agent', 160), cwd: input.cwd ? safeText(input.cwd, 'cwd', 500) : undefined, wake_reason: validateWakeReason(input.wake_reason || 'user'), createdAt: now(), status: 'manifested' }, workOrder: input.workOrder, topology, evidence: { references: [], raw: [] }, observer: { state: 'not-eligible' }, requested_next_wake: validateNextWake(input.requested_next_wake) };
    const target = this.file(this.manifests, executionId); const release = await this.lock(`manifest-${executionId}`); let result;
    try { if (await exists(target)) result = { manifest: await this.manifest(executionId), created: false }; else { await durableWrite(target, manifest, 'wx'); result = { manifest, created: true }; } } finally { await release(); }
    if (topology.parentId) await this.reconcileParent(topology.parentId); if (result.created) await this.event('manifested', { executionId, project }); return result;
  }
  async reconcileParent(parentId) { const release = await this.lock(`manifest-${parentId}`); try { const parent = await this.manifest(parentId); const all = await this.manifestsAll(); parent.topology.childIds = all.filter((m) => m.topology?.parentId === parentId).map((m) => m.execution.id).sort(); await this.atomic(this.file(this.manifests, parentId), parent); return parent; } finally { await release(); } }
  async rebuildTopology() { for (const m of await this.manifestsAll()) if (m.topology?.parentId) await this.reconcileParent(m.topology.parentId); }
  async validateAndLinkTopology(topology, executionId) {
    const checked = validateTopology(topology, executionId); if (checked.parentId && !(await exists(this.file(this.manifests, checked.parentId)))) throw new Error('topology parent does not exist');
    if (checked.rootId !== executionId && !(await exists(this.file(this.manifests, checked.rootId)))) throw new Error('topology root does not exist');
    if (checked.parentId) { const parent = await this.manifest(checked.parentId); if (parent.topology.rootId !== checked.rootId) throw new Error('topology root mismatch'); let cursor = checked.parentId, seen = new Set([executionId]); while (cursor) { if (seen.has(cursor)) throw new Error('topology cycle detected'); seen.add(cursor); cursor = (await this.manifest(cursor)).topology.parentId; } }
    return { rootId: checked.rootId, parentId: checked.parentId, childIds: [] };
  }
  async assertLease(executionId, lease) { const current = JSON.parse(await readFile(path.join(this.leases, `${enc(executionId)}.lock`), 'utf8')); if (current.owner !== lease.owner || current.fence !== lease.fence) throw new Error('lost fencing ownership'); return current; }
  async updateManifest(executionId, patch, lease) { if (lease) await this.assertLease(executionId, lease); const release = await this.lock(`manifest-${executionId}`); try { if (lease) await this.assertLease(executionId, lease); const current = await this.manifest(executionId); const next = { ...current, ...patch, execution: { ...current.execution, ...(patch.execution || {}) } }; await this.atomic(this.file(this.manifests, executionId), next); return next; } finally { await release(); } }
  async evidence(executionId, label, content, lease) {
    if (lease) await this.assertLease(executionId, lease); safeText(label, 'evidence label', 120); const data = Buffer.isBuffer(content) ? content.subarray(0, MAX_EVIDENCE) : Buffer.from(String(content)).subarray(0, MAX_EVIDENCE); const sha = digest(data); const target = path.join(this.raw, `${enc(executionId)}-${enc(label)}-${sha}.raw`);
    try { const handle = await open(target, 'wx', 0o600); try { await handle.write(data); await handle.sync(); } finally { await handle.close(); } } catch (e) { if (e.code !== 'EEXIST') throw e; }
    const reference = { uri: pathToFileURL(target).href, sha256: sha, label, bytes: data.length }; const release = await this.lock(`manifest-${executionId}`); try { if (lease) await this.assertLease(executionId, lease); const m = await this.manifest(executionId); if (!m.evidence.references.includes(reference.uri)) { m.evidence.references.push(reference.uri); m.evidence.raw.push(reference); await this.atomic(this.file(this.manifests, executionId), m); } } finally { await release(); } return reference;
  }
  async persistSemanticEvidence(executionId, envelope, lease) { await this.assertLease(executionId, lease); await this.init(); const target = path.join(this.semanticEvidence, `${envelope.envelopeId}-${envelope.contentHash}.json`); const release = await this.lock(`semantic-evidence-${executionId}`); try { await this.assertLease(executionId, lease); const names = (await readdir(this.semanticEvidence)).filter((name) => name.startsWith(`${envelope.envelopeId}-`) && name.endsWith('.json')); if (names.some((name) => name !== path.basename(target))) throw new Error('semantic evidence immutable envelope conflict'); const data = Buffer.from(json(envelope)); if (!(await exists(target))) await durableWrite(target, envelope); else if (!Buffer.from(await readFile(target)).equals(data)) throw new Error('semantic evidence immutable content conflict'); const reference = { envelopeId: envelope.envelopeId, uri: pathToFileURL(target).href, sha256: envelope.contentHash, bytes: data.length }; const m = await this.manifest(executionId); const references = [...(m.semanticEvidence?.references || [])]; const prior = references.find((item) => item.envelopeId === reference.envelopeId); if (prior && JSON.stringify(prior) !== JSON.stringify(reference)) throw new Error('semantic evidence manifest conflict'); if (!prior) { references.push(reference); await this.updateManifest(executionId, { semanticEvidence: { references } }, lease); } return reference; } finally { await release(); } }
  async semanticEvidenceFor(executionId, options = {}) { const limit = typeof options === 'number' ? options : (options.limit ?? 100); if (!Number.isSafeInteger(limit) || limit < 1 || limit > 100) throw new Error('semantic evidence limit must be from 1 to 100'); await this.init(); const m = await this.manifest(executionId); const references = m.semanticEvidence?.references || []; if (references.length > 100) throw new Error('semantic evidence manifest exceeds bounded reference limit'); const envelopes = []; for (const reference of references.slice(0, limit)) { const target = fileURLToPath(reference.uri); if (path.dirname(target) !== this.semanticEvidence || path.basename(target) !== `${reference.envelopeId}-${reference.sha256}.json`) throw new Error('semantic evidence manifest reference is invalid'); const envelope = validateSemanticEvidence(await readBoundedJson(target, MAX_RESULT)); if (envelope.envelopeId !== reference.envelopeId || envelope.contentHash !== reference.sha256 || envelope.lineage.physicalExecutionId !== executionId || m.workOrder && envelope.lineage.workOrderId !== m.workOrder) throw new Error('semantic evidence linkage is invalid'); envelopes.push(envelope); } return envelopes; }
  async retrieveSemanticEvidence(executionId, options = {}) { return this.semanticEvidenceFor(executionId, options); }
  async lease(executionId, owner = String(process.pid), staleMs = LEASE_TTL_MS) { await this.init(); const target = path.join(this.leases, `${enc(executionId)}.lock`); const release = await this.lock(`lease-${executionId}`, staleMs); try { let old = null; try { old = JSON.parse(await readFile(target, 'utf8')); } catch (e) { if (e.code !== 'ENOENT') old = null; } const ttlMs = old?.ttlMs || staleMs; if (old && Date.now() - old.heartbeatAt <= ttlMs) return { acquired: false, owner: old.owner, fence: old.fence, ttlMs }; if (old) await unlink(target).catch((e) => { if (e.code !== 'ENOENT') throw e; }); const next = { owner, fence: `${Date.now()}-${crypto.randomBytes(16).toString('hex')}`, revision: (old?.revision || 0) + 1, acquiredAt: now(), heartbeatAt: Date.now(), ttlMs: staleMs }; await durableWrite(target, next, 'wx'); if (old) await this.event('lease_recovered', { executionId, owner, previousOwner: old.owner, fence: next.fence }); return { acquired: true, ...next }; } finally { await release(); } }
  async heartbeat(executionId, lease) { const release = await this.lock(`lease-${executionId}`); try { const current = await this.assertLease(executionId, lease); current.heartbeatAt = Date.now(); await this.atomic(path.join(this.leases, `${enc(executionId)}.lock`), current); } finally { await release(); } await this.updateManifest(executionId, { execution: { lastHeartbeatAt: now() } }, lease); }
  async release(executionId, lease) { const target = path.join(this.leases, `${enc(executionId)}.lock`); const release = await this.lock(`lease-${executionId}`); try { const current = await this.assertLease(executionId, lease); if (current.fence === lease.fence) await unlink(target); } finally { await release(); } }
  async schedule(nextWake, launch = {}) { const wake = validateNextWake(nextWake); const safe = safeLaunch(launch); validateModelPolicy(safe.model, this.config); const key = digest(JSON.stringify({ wake, launch: safe })); const dir = path.join(this.root, 'schedules'); const target = this.file(dir, key); await mkdir(dir, { recursive: true }); const release = await this.lock(`schedule-${key}`); try { if (await exists(target)) return { status: 'duplicate', schedule: JSON.parse(await readFile(target, 'utf8')) }; const schedule = { schema: 'celestan-runtime-schedule-v1', id: id('wake'), key, executionId: `run-${key.slice(0, 32)}`, workOrder: `work-${key}`, wake, launch: safe, state: 'pending', createdAt: now(), recoveryAttempts: 0 }; await durableWrite(target, schedule); await this.event('scheduled', { scheduleId: schedule.id, executionId: schedule.executionId, wake }); return { status: 'scheduled', schedule }; } finally { await release(); } }
   async claimSchedules() { const dir = path.join(this.root, 'schedules'); await mkdir(dir, { recursive: true }); const out = []; for (const name of (await readdir(dir)).filter((x) => x.endsWith('.json')).sort()) { const target = path.join(dir, name), release = await this.lock(`schedule-${name}`); try { const s = JSON.parse(await readFile(target, 'utf8')); const stale = s.state === 'claimed' && Date.now() - Date.parse(s.claimedAt || s.createdAt) > LEASE_TTL_MS; if ((s.state === 'pending' || stale) && Date.parse(s.wake.time) <= Date.now()) { s.state = 'claimed'; s.claimedAt = now(); s.claimOwner = `${process.pid}-${crypto.randomBytes(8).toString('hex')}`; s.claimFence = String((BigInt(s.claimFence || 0) + 1n)); s.recoveryAttempts = stale ? (s.recoveryAttempts || 0) + 1 : (s.recoveryAttempts || 0); await this.atomic(target, s); out.push(s); } } finally { await release(); } } return out; }
   async completeSchedule(schedule, state = 'completed', claimOwner = schedule.claimOwner, claimFence = schedule.claimFence) { const target = this.file(path.join(this.root, 'schedules'), schedule.key), release = await this.lock(`schedule-${schedule.key}`); try { const current = JSON.parse(await readFile(target, 'utf8')); if (current.state === 'completed' || current.state === 'failed') return current; if (current.claimOwner !== claimOwner || String(current.claimFence) !== String(claimFence)) throw new Error('lost schedule claim ownership'); current.state = state; current.finishedAt = now(); await this.atomic(target, current); return current; } finally { await release(); } }
   async finalizeExecution(executionId, value, lease) { const manifest = await this.updateManifest(executionId, { execution: { status: value.status, finishedAt: value.finishedAt || now() }, failure: value.failure ?? null, attempts: value.attempt, output: value.output, result: value.result, modelRuntimeTelemetry: value.modelRuntimeTelemetry, requested_next_wake: value.requested_next_wake }, lease); await this.event('process_finished', value.event || { executionId, status: value.status, attempts: value.attempt }); if (value.requested_next_wake) await this.schedule(value.requested_next_wake, value.launch || {}); return manifest; }
}

function validateTopology(topology, executionId) { if (!topology || typeof topology !== 'object') throw new Error('topology must be an object'); const rootId = safeText(topology.rootId, 'topology.rootId', 180); const parentId = topology.parentId == null ? null : safeText(topology.parentId, 'topology.parentId', 180); const childIds = topology.childIds || []; if (!Array.isArray(childIds) || childIds.length > 100 || childIds.length) throw new Error('topology.childIds is authoritative and must be omitted or empty'); if (executionId === rootId && parentId) throw new Error('root cannot have a parent'); if (parentId === executionId) throw new Error('topology contains a cycle or self-link'); return { rootId, parentId, childIds: [] }; }
export { validateTopology };
export function classifyFailure(error) { const text = `${error?.code || ''} ${error?.name || ''} ${error?.message || ''}`.toLowerCase(); const category = text.includes('timeout') || text.includes('etimedout') ? 'timeout' : text.includes('network') || text.includes('econn') ? 'network' : text.includes('auth') ? 'authentication' : text.includes('provider') || text.includes('rate') || text.includes('429') ? 'provider' : text.includes('abort') || text.includes('cancel') ? 'cancellation' : text.includes('validation') || text.includes('contract') ? 'validation' : text.includes('fenc') || text.includes('lease') ? 'ownership-lost' : 'unknown'; return { category, retryable: RETRYABLE.has(category) }; }

export async function resolveExecutable(command = 'opencode') { if (process.platform !== 'win32') return command; const explicit = path.resolve(command); if (await exists(explicit)) { if (explicit.toLowerCase() === process.execPath.toLowerCase()) return explicit; if (!explicit.toLowerCase().endsWith('opencode.exe')) throw new Error('Windows runtime accepts only the opencode executable, not generic script launchers'); return explicit; } if (!['opencode', 'opencode.cmd', 'opencode.ps1'].includes(command.toLowerCase())) throw new Error('Windows runtime accepts only opencode or an explicit opencode.exe path'); const appData = process.env.APPDATA; if (!appData) throw new Error('APPDATA is unavailable; supply an explicit opencode.exe path'); const installed = path.join(appData, 'npm', 'node_modules', 'opencode-ai', 'bin', 'opencode.exe'); if (!(await exists(installed))) throw new Error(`installed OpenCode executable not found: ${installed}`); return installed; }
async function killTree(child) { if (!child.pid) return; if (process.platform === 'win32') { let succeeded = false; await new Promise((resolve) => { const killer = spawn('taskkill', ['/PID', String(child.pid), '/T', '/F'], { windowsHide: true, stdio: 'ignore' }); const timer = setTimeout(() => { killer.kill(); resolve(); }, 2000); killer.once('close', (code) => { succeeded = code === 0; clearTimeout(timer); resolve(); }); killer.once('error', () => { clearTimeout(timer); resolve(); }); }); if (!succeeded) { try { child.kill('SIGKILL'); } catch {} await wait(250); } } else { try { child.kill('SIGTERM'); } catch {} await wait(250); try { child.kill('SIGKILL'); } catch {} } }

export async function runProcess({ command = 'opencode', args = [], cwd, env = {}, secretNames = [], timeoutMs = 3600000, maxOutput = MAX_OUTPUT, onChunk = () => {}, signal } = {}) {
  const executable = await resolveExecutable(command); const orderedArgs = executable === process.execPath ? args : args.includes('run') && args.indexOf('run') > 0 ? ['run', ...args.slice(0, args.indexOf('run')), ...args.slice(args.indexOf('run') + 1)] : args; const child = spawn(executable, orderedArgs, { cwd, env: buildChildEnv(env, secretNames), stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true }); let stdout = Buffer.alloc(0), stderr = Buffer.alloc(0), truncated = { stdout: false, stderr: false }, timedOut = false, aborted = false;
  const captureMax = maxOutput + Object.values(env).filter((v) => typeof v === 'string').reduce((n, v) => Math.max(n, v.length), 0) + 4096; const add = async (stream, chunk) => { const old = stream === 'stdout' ? stdout : stderr; const room = Math.max(0, captureMax - old.length); const next = Buffer.concat([old, chunk.subarray(0, room)]); if (stream === 'stdout') stdout = next; else stderr = next; if (chunk.length > room) truncated[stream] = true; await onChunk(stream, chunk.length); };
  let writes = Promise.resolve(); child.stdout.on('data', (b) => { writes = writes.then(() => add('stdout', b)); }); child.stderr.on('data', (b) => { writes = writes.then(() => add('stderr', b)); }); const terminate = async () => { aborted = true; await killTree(child); }; const timeoutTerminate = async () => { timedOut = true; await killTree(child); }; const timer = setTimeout(timeoutTerminate, timeoutMs); const onAbort = () => { void terminate(); }; signal?.addEventListener('abort', onAbort, { once: true });
  const result = await new Promise((resolve) => { child.once('error', (error) => resolve({ error })); child.once('close', (code, signalName) => resolve({ code, signal: signalName })); }); clearTimeout(timer); signal?.removeEventListener('abort', onAbort); await writes; return { ...result, stdout: stdout.toString('utf8'), stderr: stderr.toString('utf8'), truncated, timedOut, aborted, terminated: Boolean(result.signal) || timedOut || aborted };
}
const SAFE_PROCESS_ENV = new Set(['PATH', 'HOME', 'USER', 'USERNAME', 'TMP', 'TEMP', 'TMPDIR', 'XDG_CONFIG_HOME', 'XDG_CACHE_HOME', 'XDG_DATA_HOME', 'SystemRoot', 'WINDIR', 'ComSpec', 'LANG', 'LC_ALL', 'CI']);
const DENIED_PROCESS_ENV = /(?:DATABASE|POSTGRES|MYSQL|REDIS|MONGO|S3|AWS|AZURE|GCP|GOOGLE|SECRET|TOKEN|PASSWORD|CREDENTIAL|PRIVATE.KEY|API.KEY)/i;
export function buildChildEnv(explicit = {}, secretNames = []) {
  const child = Object.fromEntries([...SAFE_PROCESS_ENV].filter((name) => process.env[name] !== undefined).map((name) => [name, process.env[name]]));
  for (const [name, value] of Object.entries(explicit)) {
    if (DENIED_PROCESS_ENV.test(name) && !secretNames.includes(name)) throw new Error(`unsafe child environment variable denied: ${name}`);
    if (value !== undefined) child[name] = String(value);
  }
  return child;
}
export function redact(text, env = {}, secretNames = Object.keys(env)) { let result = String(text); const names = new Set(secretNames); for (const [name, value] of Object.entries({ ...process.env, ...env })) if (names.has(name) && typeof value === 'string' && value.length >= 4) result = result.split(value).join('[REDACTED]'); return result; }
function boundedFields(fields) { const out = {}; for (const [key, value] of Object.entries(fields)) { if (value === undefined) continue; if (typeof value === 'string') out[key] = value.replace(/[\r\n\0]/g, ' ').slice(0, MAX_TEXT); else if (typeof value === 'number' || typeof value === 'boolean' || value === null) out[key] = value; else if (key === 'failure') out[key] = { category: value.category, retryable: Boolean(value.retryable) }; else if (key === 'aggregate') out[key] = { stdout: Math.min(0xffffffff, value.stdout || 0), stderr: Math.min(0xffffffff, value.stderr || 0), chunks: Math.min(0xffffffff, value.chunks || 0) }; else if (Array.isArray(value)) out[key] = value.slice(0, 20).map((x) => typeof x === 'string' ? x.slice(0, 120) : x); } return out; }
function safeLaunch(launch) { if (!launch || typeof launch !== 'object') throw new Error('scheduler launch configuration is required'); const out = {}; for (const key of ['command', 'model', 'agent', 'task', 'cwd', 'observerPath', 'resultFile']) if (launch[key] !== undefined) out[key] = safeText(launch[key], `launch.${key}`, key === 'task' ? 2000 : 500); if (launch.commandArgs) out.commandArgs = launch.commandArgs.map((x) => safeText(x, 'launch command argument', 2000)); if (launch.secretNames) out.secretNames = launch.secretNames.map((x) => safeText(x, 'secret name', 128)); return out; }
const RESULT_KEYS = ['requested_next_wake', 'status', 'summary'];
export function validateCelestanResult(value, secretValues = []) { if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).sort().join(',') !== RESULT_KEYS.join(',')) throw new Error('Celestan result must contain exactly status, summary, requested_next_wake'); const status = safeText(value.status, 'result.status', 32); if (!['complete', 'continue', 'failed'].includes(status)) throw new Error('result.status is invalid'); const summary = safeText(value.summary, 'result.summary', 2000); const wake = validateNextWake(value.requested_next_wake); if (secretValues.some((s) => s && [summary, JSON.stringify(wake)].some((x) => x.includes(s)))) throw new Error('result contains a supplied secret'); if (status === 'continue' && !wake) throw new Error('continue result must request next wake'); return { status, summary, requested_next_wake: wake }; }

export async function invoke({ store, executionId, command = 'opencode', commandArgs = [], model, agent, task, cwd, observerPath, env = {}, secretNames = [], timeoutMs = 3600000, dryRun = false, maxRetries = 2, resultFile, heartbeatIntervalMs } = {}) {
  if (!Number.isInteger(maxRetries) || maxRetries < 0 || maxRetries > 5) throw new Error('maxRetries must be an integer from 0 to 5'); const m = await store.manifest(executionId); if (!INVOKABLE.has(m.execution.status)) return { status: 'not-invokable', executionStatus: m.execution.status }; validateModelPolicy(model || m.execution.model, store.config); const lease = await store.lease(executionId); if (!lease.acquired) return { status: 'leased', owner: lease.owner }; const abort = new AbortController(); let heartbeatError = null; const heartbeat = setInterval(() => store.heartbeat(executionId, lease).catch((error) => { heartbeatError ||= error; abort.abort(error); }), Math.max(100, Math.min(heartbeatIntervalMs || HEARTBEAT_INTERVAL_MS, Math.floor(lease.ttlMs / 3))));
   const secrets = secretNames.map((name) => env[name]).filter((x) => typeof x === 'string'); let attempt = 0, result, failure, handoff = null, handoffDir, startedAt; const aggregate = { stdout: 0, stderr: 0, chunks: 0 };
   try {
     handoffDir = await mkdtemp(path.join(os.tmpdir(), 'ct-runtime-handoff-')); const runBase = path.join(handoffDir, enc(executionId));
      startedAt = now(); await store.updateManifest(executionId, { execution: { status: 'running', startedAt }, workOrder: m.workOrder || executionId }, lease); await persistHostSample(store, { executionId, sampleType: 'startup', coldStart: true, startedAt }); const args = [...commandArgs, 'run', '--model', safeText(model || m.execution.model, 'model', 300), '--agent', safeText(agent || m.execution.agent, 'agent', 160)];
    do { attempt++; const attemptStartedAt = now(); const resultPath = `${runBase}-attempt-${attempt}.json`; const semanticPath = `${runBase}-attempt-${attempt}-semantic.json`; if ((await exists(resultPath)) || (await exists(semanticPath))) throw Object.assign(new Error('stale preexisting result file'), { category: 'validation' }); const bootstrap = `${safeText(task || m.execution.task, 'task', 2000)}\n\nRequired CT-Runtime handoff: write exactly one JSON object to ${resultPath} with exactly these fields: status (complete|continue|failed), summary (bounded string), requested_next_wake (the exact four-field object or null). You may write a semantic evidence draft to ${semanticPath}; it must contain exactly sources and claims, with no transcript or reasoning.`; const telemetry = { stdout: 0, stderr: 0, chunks: 0 };
       result = dryRun ? { code: 0, stdout: '', stderr: '', truncated: { stdout: false, stderr: false } } : await runProcess({ command, args: [...args, bootstrap], cwd: cwd || m.execution.cwd, env: { ...env, CT_RUNTIME_RESULT_FILE: resultPath, CT_RUNTIME_SEMANTIC_EVIDENCE_FILE: semanticPath }, secretNames, timeoutMs, signal: abort.signal, onChunk: async (stream, bytes) => { telemetry[stream] += bytes; telemetry.chunks++; } });
      aggregate.stdout = Math.min(0xffffffff, aggregate.stdout + telemetry.stdout); aggregate.stderr = Math.min(0xffffffff, aggregate.stderr + telemetry.stderr); aggregate.chunks = Math.min(0xffffffff, aggregate.chunks + telemetry.chunks); await store.telemetry({ executionId, attempt, aggregate: telemetry, cumulative: aggregate, availability: 'available' }); await store.updateManifest(executionId, { modelRuntimeTelemetry: { availability: 'available', aggregate: { ...aggregate } } }, lease); if (heartbeatError) throw heartbeatError;
        failure = result.error ? classifyFailure(result.error) : result.timedOut ? { category: 'timeout', retryable: true } : result.aborted ? { category: 'ownership-lost', retryable: false } : result.signal ? { category: 'cancellation', retryable: false } : result.code === 0 ? null : classifyFailure(new Error(result.stderr || `process exit (${result.code})`)); await persistHostSample(store, { executionId, sampleType: 'execution', startedAt, finishedAt: now(), failures: failure ? [hostFailure(failure)] : [] });
      if (failure?.retryable && attempt <= maxRetries) { await store.event('retry', { executionId, attempt, category: failure.category }); await store.updateManifest(executionId, { execution: { status: 'retrying' }, attempts: attempt }, lease); }
      const inferenceFailure = failure ? normalizeInferenceFailure(result.error || { message: result.stderr || failure.category, code: result.code }) : null;
      if (!failure) { try { const raw = await readBoundedJson(resultPath, MAX_RESULT); handoff = validateCelestanResult(raw, secrets); } catch (error) { await persistInferenceAttempt(store, { workOrder: m.workOrder || executionId, executionId, agent: agent || m.execution.agent, taskPurpose: redact(task || m.execution.task, env, secretNames), modelReference: model || m.execution.model, attempt, maxRetries, startedAt: attemptStartedAt, finishedAt: now(), failure: { class: 'model/output_failure' } }); throw error; } }
      await persistInferenceAttempt(store, { workOrder: m.workOrder || executionId, executionId, agent: agent || m.execution.agent, taskPurpose: redact(task || m.execution.task, env, secretNames).replace(/[\r\n\0]/g, ' ').slice(0, MAX_TEXT), modelReference: model || m.execution.model, attempt, maxRetries, startedAt: attemptStartedAt, finishedAt: now(), failure: inferenceFailure });
    } while (failure?.retryable && attempt <= maxRetries);
      if (!failure) await persistAttemptSemanticEvidence(store, executionId, attempt, handoff, m, secrets, lease, handoffDir);
      if (heartbeatError) throw heartbeatError; const stdout = redact(result.stdout, env, secretNames).slice(0, MAX_OUTPUT), stderr = redact(result.stderr, env, secretNames).slice(0, MAX_OUTPUT); const stdoutRef = await store.evidence(executionId, `stdout-attempt-${attempt}`, stdout, lease, attempt); if (stderr) await store.evidence(executionId, `stderr-attempt-${attempt}`, stderr, lease, attempt); const status = failure ? (failure.category === 'cancellation' ? 'cancelled' : 'failed') : handoff.status === 'failed' ? 'failed' : 'success'; const finishedAt = now(), output = { stdoutTruncated: result.truncated?.stdout || result.stdout.length > MAX_OUTPUT, stderrTruncated: result.truncated?.stderr || result.stderr.length > MAX_OUTPUT }, launch = { command, commandArgs, model, agent, task, cwd, observerPath, secretNames }, event = { executionId, status, exitCode: result.code, signal: result.signal, failure, attempts: attempt }, processResult = processFacts(result), modelRuntimeTelemetry = { availability: 'available', aggregate: { ...aggregate } }; await persistHostSample(store, { executionId, sampleType: 'termination', startedAt, finishedAt, termination: status, failures: failure ? [hostFailure(failure)] : [] }); if (typeof store.finalizeExecution === 'function') await store.finalizeExecution(executionId, { status, attempt, startedAt, finishedAt, result: handoff, failure: failure || null, output, processResult, modelRuntimeTelemetry, requested_next_wake: handoff?.requested_next_wake || null, event, launch }, lease); else { await store.updateManifest(executionId, { execution: { status, finishedAt }, failure: failure || null, attempts: attempt, output, result: handoff, modelRuntimeTelemetry }, lease); await store.event('process_finished', event); if (handoff?.requested_next_wake) await store.schedule(handoff.requested_next_wake, launch); } if (failure?.retryable && ['provider', 'network'].includes(failure.category)) await store.schedule({ time: new Date(Date.now() + 60000).toISOString(), reason: 'retry', priority: 'normal', project: m.execution.project }, launch); return { status, failure: failure || null, result: { ...result, stdout, stderr }, reference: stdoutRef, attempts: attempt, handoff };
   } catch (error) { failure ||= heartbeatError ? { category: 'ownership-lost', retryable: false } : { category: error.category || 'validation', retryable: false }; const status = failure.category === 'cancellation' ? 'cancelled' : 'failed'; if (!heartbeatError && attempt > 0) { const terminal = { status, attempt, startedAt, finishedAt: now(), result: handoff, failure, output: null, processResult: processFacts(result), modelRuntimeTelemetry: { availability: 'available', aggregate: { ...aggregate } }, requested_next_wake: null, event: { executionId, status, failure, attempts: attempt }, launch: {} }; if (typeof store.finalizeExecution === 'function') await store.finalizeExecution(executionId, terminal, lease).catch(() => {}); else await store.updateManifest(executionId, { execution: { status, finishedAt: terminal.finishedAt }, failure, attempts: attempt }, lease).catch(() => {}); } return { status, attempts: attempt, failure, ...(heartbeatError ? { heartbeatError: heartbeatError.message, process: result && { terminated: result.terminated, aborted: result.aborted } } : {}) }; } finally { clearInterval(heartbeat); await store.release(executionId, lease).catch(() => {}); if (handoffDir) await rm(handoffDir, { recursive: true, force: true }).catch(() => {}); }
}

function processFacts(value) { return value ? { code: value.code ?? null, signal: value.signal ?? null, timedOut: Boolean(value.timedOut), aborted: Boolean(value.aborted), terminated: Boolean(value.terminated), truncated: value.truncated || null } : null; }
async function persistInferenceAttempt(store, fields) { if (typeof store.inferenceRecord === 'function') await store.inferenceRecord(createInferenceRecord(fields)); }
async function persistAttemptSemanticEvidence(store, executionId, attempt, handoff, manifest, secrets, lease, handoffDir) { const semanticPath = `${path.join(handoffDir, enc(executionId))}-attempt-${attempt}-semantic.json`; const handoffHash = digest(JSON.stringify(handoff)); let envelope; try { const draft = await readBoundedJson(semanticPath, MAX_RESULT); validateSemanticEvidenceDraft(draft, secrets); const sources = draft.sources.map((source) => source.sourceClass === 'execution-reported' ? { ...source, reference: `ct-runtime-result:${executionId}:${attempt}#summary`, sha256: handoffHash, sourceExecutionId: executionId } : source); if (sources.some((source) => source.sourceClass !== 'execution-reported')) throw new Error('agent semantic evidence source authority is invalid'); envelope = createSemanticEvidenceEnvelope({ lineage: { physicalExecutionId: executionId, workOrderId: manifest.workOrder || executionId }, sources, claims: draft.claims, secretValues: secrets }); } catch { if (await exists(semanticPath)) await store.event('semantic_evidence_invalid', { executionId, attempt }); const source = { sourceId: `result-${executionId}-${attempt}`, sourceClass: 'execution-reported', reference: `ct-runtime-result:${executionId}:${attempt}#summary`, sha256: handoffHash, sourceExecutionId: executionId }; envelope = createSemanticEvidenceEnvelope({ lineage: { physicalExecutionId: executionId, workOrderId: manifest.workOrder || executionId }, sources: [source], claims: [{ claimId: `summary-${executionId}-${attempt}`, claimType: 'execution-summary', statement: handoff.summary, supportSourceIds: [source.sourceId] }], secretValues: secrets }); } if (typeof store.persistSemanticEvidence !== 'function') throw new Error('durable state does not support semantic evidence'); await store.persistSemanticEvidence(executionId, envelope, lease); }
async function persistHostSample(store, fields) { if (typeof store.hostTelemetry === 'function') await store.hostTelemetry(hostTelemetry(fields), { executionId: fields.executionId }); }
function hostFailure(failure) { return { category: failure.category === 'network' ? 'network' : failure.category === 'provider' ? 'provider' : failure.category === 'cancellation' ? 'termination' : 'runtime', retryable: Boolean(failure.retryable) }; }

export async function recover({ store, staleMs = LEASE_TTL_MS } = {}) { const threshold = Math.max(LEASE_TTL_MS, staleMs); await store.rebuildTopology(); const requeued = [], crashed = []; for (const m of await store.manifestsAll()) { if (!RECOVERABLE.has(m.execution.status)) continue; const at = Date.parse(m.execution.lastHeartbeatAt || m.execution.startedAt || m.execution.createdAt); if (Number.isFinite(at) && Date.now() - at < threshold) continue; if (typeof store.recoverExecution === 'function') { const recovered = await store.recoverExecution(m.execution.id, { staleMs: threshold, maxRecovery: MAX_RECOVERY }); if (recovered) (recovered.requeued ? requeued : crashed).push(m.execution.id); continue; } const lease = await store.lease(m.execution.id, `recovery-${process.pid}`, threshold); if (!lease.acquired) continue; try { const attempt = (m.attempts || 0) + 1, recoveryAttempts = (m.recoveryAttempts || 0) + 1, shouldRequeue = recoveryAttempts <= MAX_RECOVERY; await store.updateManifest(m.execution.id, { execution: { status: shouldRequeue ? 'requeued' : 'crashed', finishedAt: now() }, failure: { category: 'crash', retryable: shouldRequeue }, attempts: attempt, recoveryAttempts, recovery: { status: shouldRequeue ? 'requeued' : 'bounded-abandonment', at: now(), interruptedAttempt: attempt } }, lease); await store.event('recovered', { executionId: m.execution.id, from: m.execution.status, requeued: shouldRequeue, attempt, recoveryAttempts }); (shouldRequeue ? requeued : crashed).push(m.execution.id); } finally { await store.release(m.execution.id, lease).catch(() => {}); } } return { status: 'recovery-complete', success: false, requeued, crashed }; }
export async function runScheduler({ store, invokeOptions = {} } = {}) { const claimed = await store.claimSchedules(), launched = [], failures = []; for (const schedule of claimed) { try { const launch = { ...schedule.launch, ...invokeOptions }; const existing = await store.manifest(schedule.executionId).catch(() => null); if (existing && TERMINAL.has(existing.execution.status)) { const succeeded = existing.execution.status === 'success'; await store.completeSchedule(schedule, succeeded ? 'completed' : 'failed', schedule.claimOwner); launched.push({ scheduleId: schedule.id, executionId: schedule.executionId, status: existing.execution.status, reinvoked: false }); if (!succeeded) failures.push({ scheduleId: schedule.id, status: existing.execution.status }); continue; } if (existing && !INVOKABLE.has(existing.execution.status)) throw new Error(`execution state ${existing.execution.status} is not invokable`); if (!launch.model || !launch.agent || !launch.task) throw new Error('scheduler launch configuration is incomplete'); const made = await store.createManifest({ executionId: schedule.executionId, workOrder: schedule.workOrder, project: schedule.wake.project, task: launch.task, model: launch.model, agent: launch.agent, cwd: launch.cwd, wake_reason: schedule.wake.reason, requested_next_wake: null }); const result = await invoke({ store, executionId: made.manifest.execution.id, ...launch }); if (result.status === 'leased') throw new Error('execution remained leased'); await store.completeSchedule(schedule, result.status === 'success' ? 'completed' : 'failed', schedule.claimOwner); launched.push({ scheduleId: schedule.id, executionId: schedule.executionId, status: result.status }); if (result.status !== 'success') failures.push({ scheduleId: schedule.id, status: result.status }); } catch (error) { failures.push({ scheduleId: schedule.id, error: error.message.slice(0, 200) }); await store.completeSchedule(schedule, 'failed', schedule.claimOwner).catch(() => {}); } } return { claimed, launched, failures, success: failures.length === 0 }; }

export async function observePending({ store, observerPath, semanticResultFile, reflection = {} } = {}) { if (!observerPath) throw new Error('observer path is required'); const mod = await import(pathToFileURL(observerPath)); const observerStore = new mod.ObserverStore(path.join(store.root, 'observer')); const out = []; for (const m of await store.manifestsAll()) { if (!TERMINAL.has(m.execution.status) || m.observer?.state === 'observed' || m.execution.agent?.toLowerCase() === 'observer') continue; const semanticPath = semanticResultFile || reflection.resultFile; await store.updateManifest(m.execution.id, { observer: { state: 'pending', pendingAt: m.observer?.pendingAt || now() } }); try { const envelope = (await store.semanticEvidenceFor(m.execution.id, { limit: 100 }))[0]; const telemetry = m.modelRuntimeTelemetry?.availability === 'available' ? m.modelRuntimeTelemetry : { availability: 'unavailable', reason: 'not-exposed' }; const evidence = { source: 'ct-runtime', references: m.evidence.raw.map((r) => r.uri), evidenceDigest: digest(JSON.stringify(m.evidence)), observerMeta: { runtime: 'ct-runtime', status: m.execution.status }, modelRuntimeTelemetry: telemetry }; const input = { execution: { executionId: m.execution.id, project: m.execution.project, status: m.execution.status, startedAt: m.execution.startedAt, finishedAt: m.execution.finishedAt }, evidence, ...(envelope ? { evidenceEnvelope: envelope } : {}) }; if (semanticPath && envelope) { const semantic = await readBoundedJson(semanticPath, MAX_RESULT); input.semantic = (_digest, join) => ({ ...semantic, evidenceBasis: semantic.evidenceBasis || { bindingHash: join.bindingHash, claimReferences: join.claimReferences } }); } const r = await mod.digestAndAppend(observerStore, input); if (!envelope) { await store.updateManifest(m.execution.id, { observer: { state: 'not-eligible' } }); out.push({ executionId: m.execution.id, status: 'semantic-evidence-insufficient' }); continue; } if (r.result.status === 'duplicate') { const existing = await readBoundedJson(observerStore.recordPath(m.execution.id), MAX_RESULT); if (JSON.stringify(existing.provenance) !== JSON.stringify(r.digest.provenance)) throw new Error('immutable Observer provenance conflict'); } if (input.semantic) { await store.updateManifest(m.execution.id, { observer: { state: 'observed', observedAt: now() } }); out.push({ executionId: m.execution.id, status: 'observed' }); } else out.push({ executionId: m.execution.id, status: 'semantic-analysis-pending' }); } catch (error) { await store.event('observer_pending', { executionId: m.execution.id, error: error.message }); out.push({ executionId: m.execution.id, status: 'semantic-analysis-pending' }); } } return out; }
