import { appendFile, mkdir, open, readFile, readdir, rename, stat, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';

export const WAKE_REASONS = Object.freeze(['scheduled', 'user', 'webhook', 'github', 'retry', 'self_scheduled', 'observer', 'maintenance']);
export const LEASE_TTL_MS = 300000;
export const HEARTBEAT_INTERVAL_MS = Math.floor(LEASE_TTL_MS / 3);
const RETRYABLE = new Set(['timeout', 'network', 'provider']);
const TERMINAL = new Set(['success', 'failed', 'cancelled', 'crashed']);
const INVOKABLE = new Set(['manifested', 'requeued', 'retrying']);
const RECOVERABLE = new Set([...INVOKABLE, 'running']);
const MAX_TEXT = 500, MAX_OUTPUT = 64 * 1024, MAX_EVIDENCE = 64 * 1024, MAX_RESULT = 64 * 1024, MAX_RECOVERY = 3;
const safeText = (v, field, max = MAX_TEXT) => { if (typeof v !== 'string' || !v.trim() || v.length > max || /[\0\r\n]/.test(v)) throw new Error(`${field} must be a bounded safe string`); return v; };
const id = (prefix = 'x') => `${prefix}-${Date.now().toString(36)}-${crypto.randomBytes(12).toString('hex')}`;
const digest = (data) => crypto.createHash('sha256').update(data).digest('hex');
const json = (v) => JSON.stringify(v, null, 2) + '\n';
const now = () => new Date().toISOString();
const exists = async (p) => { try { await stat(p); return true; } catch { return false; } };
const enc = (value) => encodeURIComponent(value);
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export function validateWakeReason(reason) { if (!WAKE_REASONS.includes(reason)) throw new Error(`wake_reason must be one of: ${WAKE_REASONS.join(', ')}`); return reason; }
export function validateNextWake(value) {
  if (value === null || value === undefined) return null;
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('requested_next_wake must be an object or null');
  if (Object.keys(value).sort().join(',') !== 'priority,project,reason,time') throw new Error('requested_next_wake has unexpected fields');
  const time = safeText(value.time, 'requested_next_wake.time', 64); if (Number.isNaN(Date.parse(time))) throw new Error('requested_next_wake.time must be an ISO timestamp');
  return { time, reason: validateWakeReason(value.reason), priority: safeText(value.priority, 'requested_next_wake.priority', 32), project: safeText(value.project, 'requested_next_wake.project', 160) };
}

async function durableWrite(target, value, flag = 'w') {
  await mkdir(path.dirname(target), { recursive: true });
  const temp = `${target}.${process.pid}.${crypto.randomBytes(6).toString('hex')}.tmp`;
  const handle = await open(temp, flag === 'wx' ? 'wx' : 'w', 0o600);
  try { await handle.writeFile(json(value)); await handle.sync(); } finally { await handle.close(); }
  await rename(temp, target);
  let dir; try { dir = await open(path.dirname(target), 'r'); await dir.sync(); } catch { /* unsupported directory fsync */ } finally { await dir?.close().catch(() => {}); }
}

async function readBoundedJson(target, maximum) {
  const handle = await open(target, 'r');
  try { const info = await handle.stat(); if (info.size > maximum) throw Object.assign(new Error('bounded file exceeds hard limit'), { category: 'validation' }); return JSON.parse(await handle.readFile('utf8')); }
  finally { await handle.close(); }
}

export class Store {
  constructor(root) { if (!root) throw new Error('store path is required'); this.root = path.resolve(root); this.manifests = path.join(this.root, 'manifests'); this.raw = path.join(this.root, 'raw'); this.leases = path.join(this.root, 'leases'); this.locks = path.join(this.root, 'locks'); this.results = path.join(this.root, 'results'); }
  async init() { await Promise.all([mkdir(this.manifests, { recursive: true }), mkdir(this.raw, { recursive: true }), mkdir(this.leases, { recursive: true }), mkdir(this.locks, { recursive: true }), mkdir(this.results, { recursive: true })]); }
  file(dir, name) { return path.join(dir, `${enc(name)}.json`); }
  async atomic(target, value) { return durableWrite(target, value); }
  async manifest(executionId) { return JSON.parse(await readFile(this.file(this.manifests, executionId), 'utf8')); }
  async manifestsAll() { await this.init(); return Promise.all((await readdir(this.manifests)).filter((x) => x.endsWith('.json')).sort().map((x) => readFile(path.join(this.manifests, x), 'utf8').then(JSON.parse))); }
  async append(kind, record) { await this.init(); const handle = await open(path.join(this.root, `${kind}.ndjson`), 'a', 0o600); try { await handle.writeFile(JSON.stringify(record) + '\n'); await handle.sync(); } finally { await handle.close(); } }
  async event(type, fields = {}) { await this.append('events', { schema: 'celestan-runtime-event-v1', id: id('evt'), at: now(), type: safeText(type, 'event type', 64), ...boundedFields(fields) }); }
  async telemetry(fields = {}) { await this.append('telemetry', { schema: 'celestan-runtime-telemetry-v1', id: id('tel'), at: now(), ...boundedFields(fields) }); }
  async lock(name, staleMs = LEASE_TTL_MS) {
    await this.init(); const target = path.join(this.locks, `${enc(name)}.lock`); const token = `${process.pid}-${crypto.randomBytes(12).toString('hex')}`; const deadline = Date.now() + Math.max(staleMs, 1000) * 2;
    for (;;) try { await writeFile(target, JSON.stringify({ token, at: Date.now() }), { flag: 'wx', mode: 0o600 }); return async () => { try { if ((await JSON.parse(await readFile(target, 'utf8'))).token === token) await unlink(target); } catch (e) { if (e.code !== 'ENOENT') throw e; } }; }
    catch (e) { if (!['EEXIST', 'EPERM', 'EBUSY'].includes(e.code)) throw e; try { const old = JSON.parse(await readFile(target, 'utf8')); if (Date.now() - old.at > staleMs) await unlink(target).catch(() => {}); else await wait(5); } catch (x) { if (Date.now() > deadline) throw new Error('lock contention exceeded bounded deadline'); if (x.code !== 'ENOENT') await wait(5); } }
  }
  async createManifest(input) {
    await this.init(); const executionId = input.executionId || id('run'); safeText(executionId, 'executionId', 180); const project = safeText(input.project, 'project', 160);
    const topology = await this.validateAndLinkTopology(input.topology || { rootId: executionId, childIds: [] }, executionId);
    const manifest = { schema: 'celestan-runtime-manifest-v1', execution: { id: executionId, project, task: safeText(input.task, 'task', 2000), model: safeText(input.model, 'model', 300), agent: safeText(input.agent, 'agent', 160), cwd: input.cwd ? safeText(input.cwd, 'cwd', 500) : undefined, wake_reason: validateWakeReason(input.wake_reason || 'user'), createdAt: now(), status: 'manifested' }, workOrder: input.workOrder, topology, evidence: { references: [], raw: [] }, observer: { state: 'not-eligible' }, requested_next_wake: validateNextWake(input.requested_next_wake) };
    const target = this.file(this.manifests, executionId); const release = await this.lock(`manifest-${executionId}`); let result;
    try { if (await exists(target)) result = { manifest: await this.manifest(executionId), created: false }; else { await durableWrite(target, manifest, 'wx'); result = { manifest, created: true }; } } finally { await release(); }
    if (topology.parentId) await this.reconcileParent(topology.parentId); if (result.created) await this.event('manifested', { executionId, project }); return result;
  }
  async reconcileParent(parentId) { const release = await this.lock(`manifest-${parentId}`); try { const parent = await this.manifest(parentId); const all = await this.manifestsAll(); parent.topology.childIds = all.filter((m) => m.topology?.parentId === parentId).map((m) => m.execution.id).sort(); await this.atomic(this.file(this.manifests, parentId), parent); return parent; } finally { await release(); } }
  async rebuildTopology() { for (const m of await this.manifestsAll()) if (m.topology?.parentId) await this.reconcileParent(m.topology.parentId); }
  async validateAndLinkTopology(topology, executionId) {
    const checked = validateTopology(topology, executionId); if (checked.parentId && !(await exists(this.file(this.manifests, checked.parentId)))) throw new Error('topology parent does not exist');
    if (checked.rootId !== executionId && !(await exists(this.file(this.manifests, checked.rootId)))) throw new Error('topology root does not exist');
    if (checked.parentId) { const parent = await this.manifest(checked.parentId); if (parent.topology.rootId !== checked.rootId) throw new Error('topology root mismatch'); let cursor = checked.parentId, seen = new Set([executionId]); while (cursor) { if (seen.has(cursor)) throw new Error('topology cycle detected'); seen.add(cursor); cursor = (await this.manifest(cursor)).topology.parentId; } }
    return { rootId: checked.rootId, parentId: checked.parentId, childIds: [] };
  }
  async assertLease(executionId, lease) { const current = JSON.parse(await readFile(path.join(this.leases, `${enc(executionId)}.lock`), 'utf8')); if (current.owner !== lease.owner || current.fence !== lease.fence) throw new Error('lost fencing ownership'); return current; }
  async updateManifest(executionId, patch, lease) { if (lease) await this.assertLease(executionId, lease); const release = await this.lock(`manifest-${executionId}`); try { if (lease) await this.assertLease(executionId, lease); const current = await this.manifest(executionId); const next = { ...current, ...patch, execution: { ...current.execution, ...(patch.execution || {}) } }; await this.atomic(this.file(this.manifests, executionId), next); return next; } finally { await release(); } }
  async evidence(executionId, label, content, lease) {
    if (lease) await this.assertLease(executionId, lease); safeText(label, 'evidence label', 120); const data = Buffer.isBuffer(content) ? content.subarray(0, MAX_EVIDENCE) : Buffer.from(String(content)).subarray(0, MAX_EVIDENCE); const sha = digest(data); const target = path.join(this.raw, `${enc(executionId)}-${enc(label)}-${sha}.raw`);
    try { const handle = await open(target, 'wx', 0o600); try { await handle.write(data); await handle.sync(); } finally { await handle.close(); } } catch (e) { if (e.code !== 'EEXIST') throw e; }
    const reference = { uri: pathToFileURL(target).href, sha256: sha, label, bytes: data.length }; const release = await this.lock(`manifest-${executionId}`); try { if (lease) await this.assertLease(executionId, lease); const m = await this.manifest(executionId); if (!m.evidence.references.includes(reference.uri)) { m.evidence.references.push(reference.uri); m.evidence.raw.push(reference); await this.atomic(this.file(this.manifests, executionId), m); } } finally { await release(); } return reference;
  }
  async lease(executionId, owner = String(process.pid), staleMs = LEASE_TTL_MS) { await this.init(); const target = path.join(this.leases, `${enc(executionId)}.lock`); const release = await this.lock(`lease-${executionId}`, staleMs); try { let old = null; try { old = JSON.parse(await readFile(target, 'utf8')); } catch (e) { if (e.code !== 'ENOENT') old = null; } const ttlMs = old?.ttlMs || staleMs; if (old && Date.now() - old.heartbeatAt <= ttlMs) return { acquired: false, owner: old.owner, fence: old.fence, ttlMs }; if (old) await unlink(target).catch((e) => { if (e.code !== 'ENOENT') throw e; }); const next = { owner, fence: `${Date.now()}-${crypto.randomBytes(16).toString('hex')}`, revision: (old?.revision || 0) + 1, acquiredAt: now(), heartbeatAt: Date.now(), ttlMs: staleMs }; await durableWrite(target, next, 'wx'); if (old) await this.event('lease_recovered', { executionId, owner, previousOwner: old.owner, fence: next.fence }); return { acquired: true, ...next }; } finally { await release(); } }
  async heartbeat(executionId, lease) { const release = await this.lock(`lease-${executionId}`); try { const current = await this.assertLease(executionId, lease); current.heartbeatAt = Date.now(); await this.atomic(path.join(this.leases, `${enc(executionId)}.lock`), current); } finally { await release(); } await this.updateManifest(executionId, { execution: { lastHeartbeatAt: now() } }, lease); }
  async release(executionId, lease) { const target = path.join(this.leases, `${enc(executionId)}.lock`); const release = await this.lock(`lease-${executionId}`); try { const current = await this.assertLease(executionId, lease); if (current.fence === lease.fence) await unlink(target); } finally { await release(); } }
  async schedule(nextWake, launch = {}) { const wake = validateNextWake(nextWake); const safe = safeLaunch(launch); const key = digest(JSON.stringify({ wake, launch: safe })); const dir = path.join(this.root, 'schedules'); const target = this.file(dir, key); await mkdir(dir, { recursive: true }); const release = await this.lock(`schedule-${key}`); try { if (await exists(target)) return { status: 'duplicate', schedule: JSON.parse(await readFile(target, 'utf8')) }; const schedule = { schema: 'celestan-runtime-schedule-v1', id: id('wake'), key, executionId: `run-${key.slice(0, 32)}`, workOrder: `work-${key}`, wake, launch: safe, state: 'pending', createdAt: now(), recoveryAttempts: 0 }; await durableWrite(target, schedule); await this.event('scheduled', { scheduleId: schedule.id, executionId: schedule.executionId, wake }); return { status: 'scheduled', schedule }; } finally { await release(); } }
  async claimSchedules() { const dir = path.join(this.root, 'schedules'); await mkdir(dir, { recursive: true }); const out = []; for (const name of (await readdir(dir)).filter((x) => x.endsWith('.json')).sort()) { const target = path.join(dir, name), release = await this.lock(`schedule-${name}`); try { const s = JSON.parse(await readFile(target, 'utf8')); const stale = s.state === 'claimed' && Date.now() - Date.parse(s.claimedAt || s.createdAt) > LEASE_TTL_MS; if ((s.state === 'pending' || stale) && Date.parse(s.wake.time) <= Date.now()) { s.state = 'claimed'; s.claimedAt = now(); s.claimOwner = `${process.pid}-${crypto.randomBytes(8).toString('hex')}`; await this.atomic(target, s); out.push(s); } } finally { await release(); } } return out; }
  async completeSchedule(schedule, state = 'completed', claimOwner = schedule.claimOwner) { const target = this.file(path.join(this.root, 'schedules'), schedule.key), release = await this.lock(`schedule-${schedule.key}`); try { const current = JSON.parse(await readFile(target, 'utf8')); if (current.state === 'completed' || current.state === 'failed') return current; if (current.claimOwner !== claimOwner) throw new Error('lost schedule claim ownership'); current.state = state; current.finishedAt = now(); await this.atomic(target, current); return current; } finally { await release(); } }
}

function validateTopology(topology, executionId) { if (!topology || typeof topology !== 'object') throw new Error('topology must be an object'); const rootId = safeText(topology.rootId, 'topology.rootId', 180); const parentId = topology.parentId == null ? null : safeText(topology.parentId, 'topology.parentId', 180); const childIds = topology.childIds || []; if (!Array.isArray(childIds) || childIds.length > 100 || childIds.length) throw new Error('topology.childIds is authoritative and must be omitted or empty'); if (executionId === rootId && parentId) throw new Error('root cannot have a parent'); if (parentId === executionId) throw new Error('topology contains a cycle or self-link'); return { rootId, parentId, childIds: [] }; }
export { validateTopology };
export function classifyFailure(error) { const text = `${error?.code || ''} ${error?.name || ''} ${error?.message || ''}`.toLowerCase(); const category = text.includes('timeout') || text.includes('etimedout') ? 'timeout' : text.includes('network') || text.includes('econn') ? 'network' : text.includes('auth') ? 'authentication' : text.includes('provider') || text.includes('rate') || text.includes('429') ? 'provider' : text.includes('abort') || text.includes('cancel') ? 'cancellation' : text.includes('validation') || text.includes('contract') ? 'validation' : text.includes('fenc') || text.includes('lease') ? 'ownership-lost' : 'unknown'; return { category, retryable: RETRYABLE.has(category) }; }

export async function resolveExecutable(command = 'opencode') { if (process.platform !== 'win32') return command; const explicit = path.resolve(command); if (await exists(explicit)) { if (explicit.toLowerCase() === process.execPath.toLowerCase()) return explicit; if (!explicit.toLowerCase().endsWith('opencode.exe')) throw new Error('Windows runtime accepts only the opencode executable, not generic script launchers'); return explicit; } if (!['opencode', 'opencode.cmd', 'opencode.ps1'].includes(command.toLowerCase())) throw new Error('Windows runtime accepts only opencode or an explicit opencode.exe path'); const appData = process.env.APPDATA; if (!appData) throw new Error('APPDATA is unavailable; supply an explicit opencode.exe path'); const installed = path.join(appData, 'npm', 'node_modules', 'opencode-ai', 'bin', 'opencode.exe'); if (!(await exists(installed))) throw new Error(`installed OpenCode executable not found: ${installed}`); return installed; }
async function killTree(child) { if (!child.pid) return; if (process.platform === 'win32') { let succeeded = false; await new Promise((resolve) => { const killer = spawn('taskkill', ['/PID', String(child.pid), '/T', '/F'], { windowsHide: true, stdio: 'ignore' }); const timer = setTimeout(() => { killer.kill(); resolve(); }, 2000); killer.once('close', (code) => { succeeded = code === 0; clearTimeout(timer); resolve(); }); killer.once('error', () => { clearTimeout(timer); resolve(); }); }); if (!succeeded) { try { child.kill('SIGKILL'); } catch {} await wait(250); } } else { try { child.kill('SIGTERM'); } catch {} await wait(250); try { child.kill('SIGKILL'); } catch {} } }

export async function runProcess({ command = 'opencode', args = [], cwd, env = {}, timeoutMs = 3600000, maxOutput = MAX_OUTPUT, onChunk = () => {}, signal } = {}) {
  const executable = await resolveExecutable(command); const orderedArgs = executable === process.execPath ? args : args.includes('run') && args.indexOf('run') > 0 ? ['run', ...args.slice(0, args.indexOf('run')), ...args.slice(args.indexOf('run') + 1)] : args; const child = spawn(executable, orderedArgs, { cwd, env: { ...process.env, ...env }, stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true }); let stdout = Buffer.alloc(0), stderr = Buffer.alloc(0), truncated = { stdout: false, stderr: false }, timedOut = false, aborted = false;
  const captureMax = maxOutput + Object.values(env).filter((v) => typeof v === 'string').reduce((n, v) => Math.max(n, v.length), 0) + 4096; const add = async (stream, chunk) => { const old = stream === 'stdout' ? stdout : stderr; const room = Math.max(0, captureMax - old.length); const next = Buffer.concat([old, chunk.subarray(0, room)]); if (stream === 'stdout') stdout = next; else stderr = next; if (chunk.length > room) truncated[stream] = true; await onChunk(stream, chunk.length); };
  let writes = Promise.resolve(); child.stdout.on('data', (b) => { writes = writes.then(() => add('stdout', b)); }); child.stderr.on('data', (b) => { writes = writes.then(() => add('stderr', b)); }); const terminate = async () => { aborted = true; await killTree(child); }; const timeoutTerminate = async () => { timedOut = true; await killTree(child); }; const timer = setTimeout(timeoutTerminate, timeoutMs); const onAbort = () => { void terminate(); }; signal?.addEventListener('abort', onAbort, { once: true });
  const result = await new Promise((resolve) => { child.once('error', (error) => resolve({ error })); child.once('close', (code, signalName) => resolve({ code, signal: signalName })); }); clearTimeout(timer); signal?.removeEventListener('abort', onAbort); await writes; return { ...result, stdout: stdout.toString('utf8'), stderr: stderr.toString('utf8'), truncated, timedOut, aborted, terminated: Boolean(result.signal) || timedOut || aborted };
}
export function redact(text, env = {}, secretNames = Object.keys(env)) { let result = String(text); const names = new Set(secretNames); for (const [name, value] of Object.entries({ ...process.env, ...env })) if (names.has(name) && typeof value === 'string' && value.length >= 4) result = result.split(value).join('[REDACTED]'); return result; }
function boundedFields(fields) { const out = {}; for (const [key, value] of Object.entries(fields)) { if (value === undefined) continue; if (typeof value === 'string') out[key] = value.replace(/[\r\n\0]/g, ' ').slice(0, MAX_TEXT); else if (typeof value === 'number' || typeof value === 'boolean' || value === null) out[key] = value; else if (key === 'failure') out[key] = { category: value.category, retryable: Boolean(value.retryable) }; else if (key === 'aggregate') out[key] = { stdout: Math.min(0xffffffff, value.stdout || 0), stderr: Math.min(0xffffffff, value.stderr || 0), chunks: Math.min(0xffffffff, value.chunks || 0) }; else if (Array.isArray(value)) out[key] = value.slice(0, 20).map((x) => typeof x === 'string' ? x.slice(0, 120) : x); } return out; }
function safeLaunch(launch) { if (!launch || typeof launch !== 'object') throw new Error('scheduler launch configuration is required'); const out = {}; for (const key of ['command', 'model', 'agent', 'task', 'cwd', 'observerPath', 'resultFile']) if (launch[key] !== undefined) out[key] = safeText(launch[key], `launch.${key}`, key === 'task' ? 2000 : 500); if (launch.commandArgs) out.commandArgs = launch.commandArgs.map((x) => safeText(x, 'launch command argument', 2000)); if (launch.secretNames) out.secretNames = launch.secretNames.map((x) => safeText(x, 'secret name', 128)); return out; }
const RESULT_KEYS = ['requested_next_wake', 'status', 'summary'];
export function validateCelestanResult(value, secretValues = []) { if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).sort().join(',') !== RESULT_KEYS.join(',')) throw new Error('Celestan result must contain exactly status, summary, requested_next_wake'); const status = safeText(value.status, 'result.status', 32); if (!['complete', 'continue', 'failed'].includes(status)) throw new Error('result.status is invalid'); const summary = safeText(value.summary, 'result.summary', 2000); const wake = validateNextWake(value.requested_next_wake); if (secretValues.some((s) => s && [summary, JSON.stringify(wake)].some((x) => x.includes(s)))) throw new Error('result contains a supplied secret'); if (status === 'continue' && !wake) throw new Error('continue result must request next wake'); return { status, summary, requested_next_wake: wake }; }

export async function invoke({ store, executionId, command = 'opencode', commandArgs = [], model, agent, task, cwd, observerPath, env = {}, secretNames = [], timeoutMs = 3600000, dryRun = false, maxRetries = 2, resultFile, heartbeatIntervalMs } = {}) {
  if (!Number.isInteger(maxRetries) || maxRetries < 0 || maxRetries > 5) throw new Error('maxRetries must be an integer from 0 to 5'); const m = await store.manifest(executionId); if (!INVOKABLE.has(m.execution.status)) return { status: 'not-invokable', executionStatus: m.execution.status }; const lease = await store.lease(executionId); if (!lease.acquired) return { status: 'leased', owner: lease.owner }; const abort = new AbortController(); let heartbeatError = null; const heartbeat = setInterval(() => store.heartbeat(executionId, lease).catch((error) => { heartbeatError ||= error; abort.abort(error); }), Math.max(100, Math.min(heartbeatIntervalMs || HEARTBEAT_INTERVAL_MS, Math.floor(lease.ttlMs / 3))));
  const secrets = secretNames.map((name) => ({ name, value: { ...process.env, ...env }[name] })).map((x) => x.value).filter((x) => typeof x === 'string'); let attempt = 0, result, failure, handoff = null; const runBase = resultFile ? safeText(resultFile, 'resultFile', 1000) : path.join(store.results, enc(executionId)); const aggregate = { stdout: 0, stderr: 0, chunks: 0 };
  try {
    await store.updateManifest(executionId, { execution: { status: 'running', startedAt: now() }, workOrder: m.workOrder || executionId }, lease); const args = [...commandArgs, 'run', '--model', safeText(model || m.execution.model, 'model', 300), '--agent', safeText(agent || m.execution.agent, 'agent', 160)];
    do { attempt++; const resultPath = `${runBase}-attempt-${attempt}.json`; if (await exists(resultPath)) throw Object.assign(new Error('stale preexisting result file'), { category: 'validation' }); const bootstrap = `${safeText(task || m.execution.task, 'task', 2000)}\n\nRequired CT-Runtime handoff: write exactly one JSON object to ${resultPath} with exactly these fields: status (complete|continue|failed), summary (bounded string), requested_next_wake (the exact four-field object or null).`; const telemetry = { stdout: 0, stderr: 0, chunks: 0 };
      result = dryRun ? { code: 0, stdout: '', stderr: '', truncated: { stdout: false, stderr: false } } : await runProcess({ command, args: [...args, bootstrap], cwd: cwd || m.execution.cwd, env: { ...env, CT_RUNTIME_RESULT_FILE: resultPath }, timeoutMs, signal: abort.signal, onChunk: async (stream, bytes) => { telemetry[stream] += bytes; telemetry.chunks++; } });
      aggregate.stdout = Math.min(0xffffffff, aggregate.stdout + telemetry.stdout); aggregate.stderr = Math.min(0xffffffff, aggregate.stderr + telemetry.stderr); aggregate.chunks = Math.min(0xffffffff, aggregate.chunks + telemetry.chunks); await store.telemetry({ executionId, attempt, aggregate: telemetry, cumulative: aggregate, availability: 'available' }); await store.updateManifest(executionId, { modelRuntimeTelemetry: { availability: 'available', aggregate: { ...aggregate } } }, lease); if (heartbeatError) throw heartbeatError;
      failure = result.error ? classifyFailure(result.error) : result.timedOut ? { category: 'timeout', retryable: true } : result.aborted ? { category: 'ownership-lost', retryable: false } : result.signal ? { category: 'cancellation', retryable: false } : result.code === 0 ? null : classifyFailure(new Error('process exit'));
      if (failure?.retryable && attempt <= maxRetries) { await store.event('retry', { executionId, attempt, category: failure.category }); await store.updateManifest(executionId, { execution: { status: 'retrying' }, attempts: attempt }, lease); }
      if (!failure) { const raw = await readBoundedJson(resultPath, MAX_RESULT); handoff = validateCelestanResult(raw, secrets); }
    } while (failure?.retryable && attempt <= maxRetries);
    if (heartbeatError) throw heartbeatError; const stdout = redact(result.stdout, env, secretNames).slice(0, MAX_OUTPUT), stderr = redact(result.stderr, env, secretNames).slice(0, MAX_OUTPUT); const stdoutRef = await store.evidence(executionId, `stdout-attempt-${attempt}`, stdout, lease); if (stderr) await store.evidence(executionId, `stderr-attempt-${attempt}`, stderr, lease); const status = failure ? (failure.category === 'cancellation' ? 'cancelled' : 'failed') : handoff.status === 'failed' ? 'failed' : 'success'; await store.updateManifest(executionId, { execution: { status, finishedAt: now() }, failure: failure || null, attempts: attempt, output: { stdoutTruncated: result.truncated?.stdout || result.stdout.length > MAX_OUTPUT, stderrTruncated: result.truncated?.stderr || result.stderr.length > MAX_OUTPUT }, result: handoff }, lease); await store.event('process_finished', { executionId, status, exitCode: result.code, signal: result.signal, failure, attempts: attempt }); if (handoff?.requested_next_wake) await store.schedule(handoff.requested_next_wake, { command, commandArgs, model, agent, task, cwd, observerPath, secretNames }); return { status, result: { ...result, stdout, stderr }, reference: stdoutRef, attempts: attempt, handoff };
  } catch (error) { failure ||= heartbeatError ? { category: 'ownership-lost', retryable: false } : { category: error.category || 'validation', retryable: false }; const status = failure.category === 'cancellation' ? 'cancelled' : 'failed'; if (!heartbeatError) await store.updateManifest(executionId, { execution: { status, finishedAt: now() }, failure, attempts: attempt }, lease).catch(() => {}); return { status, attempts: attempt, failure, ...(heartbeatError ? { heartbeatError: heartbeatError.message, process: result && { terminated: result.terminated, aborted: result.aborted } } : {}) }; } finally { clearInterval(heartbeat); await store.release(executionId, lease).catch(() => {}); }
}

export async function recover({ store, staleMs = LEASE_TTL_MS } = {}) { const threshold = Math.max(LEASE_TTL_MS, staleMs); await store.rebuildTopology(); const requeued = [], crashed = []; for (const m of await store.manifestsAll()) { if (!RECOVERABLE.has(m.execution.status)) continue; const at = Date.parse(m.execution.lastHeartbeatAt || m.execution.startedAt || m.execution.createdAt); if (Number.isFinite(at) && Date.now() - at < threshold) continue; const lease = await store.lease(m.execution.id, `recovery-${process.pid}`, threshold); if (!lease.acquired) continue; try { const attempts = (m.attempts || 0) + 1; await store.updateManifest(m.execution.id, { execution: { status: attempts <= MAX_RECOVERY ? 'requeued' : 'crashed', finishedAt: now() }, failure: { category: 'crash', retryable: attempts <= MAX_RECOVERY }, attempts, recovery: { status: attempts <= MAX_RECOVERY ? 'requeued' : 'bounded-abandonment', at: now(), interruptedAttempt: attempts } }, lease); await store.event('recovered', { executionId: m.execution.id, from: m.execution.status, requeued: attempts <= MAX_RECOVERY, attempt: attempts }); (attempts <= MAX_RECOVERY ? requeued : crashed).push(m.execution.id); } finally { await store.release(m.execution.id, lease).catch(() => {}); } } return { status: 'recovery-complete', success: false, requeued, crashed }; }
export async function runScheduler({ store, invokeOptions = {} } = {}) { const claimed = await store.claimSchedules(), launched = [], failures = []; for (const schedule of claimed) { try { const launch = { ...schedule.launch, ...invokeOptions }; const existing = await store.manifest(schedule.executionId).catch(() => null); if (existing && TERMINAL.has(existing.execution.status)) { const succeeded = existing.execution.status === 'success'; await store.completeSchedule(schedule, succeeded ? 'completed' : 'failed', schedule.claimOwner); launched.push({ scheduleId: schedule.id, executionId: schedule.executionId, status: existing.execution.status, reinvoked: false }); if (!succeeded) failures.push({ scheduleId: schedule.id, status: existing.execution.status }); continue; } if (existing && !INVOKABLE.has(existing.execution.status)) throw new Error(`execution state ${existing.execution.status} is not invokable`); if (!launch.model || !launch.agent || !launch.task) throw new Error('scheduler launch configuration is incomplete'); const made = await store.createManifest({ executionId: schedule.executionId, workOrder: schedule.workOrder, project: schedule.wake.project, task: launch.task, model: launch.model, agent: launch.agent, cwd: launch.cwd, wake_reason: schedule.wake.reason, requested_next_wake: null }); const result = await invoke({ store, executionId: made.manifest.execution.id, ...launch }); if (result.status === 'leased') throw new Error('execution remained leased'); await store.completeSchedule(schedule, result.status === 'success' ? 'completed' : 'failed', schedule.claimOwner); launched.push({ scheduleId: schedule.id, executionId: schedule.executionId, status: result.status }); if (result.status !== 'success') failures.push({ scheduleId: schedule.id, status: result.status }); } catch (error) { failures.push({ scheduleId: schedule.id, error: error.message.slice(0, 200) }); await store.completeSchedule(schedule, 'failed', schedule.claimOwner).catch(() => {}); } } return { claimed, launched, failures, success: failures.length === 0 }; }

export async function observePending({ store, observerPath, semanticResultFile, reflection = {} } = {}) { if (!observerPath) throw new Error('observer path is required'); const mod = await import(pathToFileURL(observerPath)); const observerStore = new mod.ObserverStore(path.join(store.root, 'observer')); const out = []; for (const m of await store.manifestsAll()) { if (!TERMINAL.has(m.execution.status) || m.observer?.state === 'observed' || m.execution.agent?.toLowerCase() === 'observer') continue; const semanticPath = semanticResultFile || reflection.resultFile; await store.updateManifest(m.execution.id, { observer: { state: 'pending', pendingAt: m.observer?.pendingAt || now() } }); try { const telemetry = m.modelRuntimeTelemetry?.availability === 'available' ? m.modelRuntimeTelemetry : { availability: 'unavailable', reason: 'not-exposed' }; const evidence = { source: 'ct-runtime', references: m.evidence.raw.map((r) => r.uri), evidenceDigest: digest(JSON.stringify(m.evidence)), observerMeta: { runtime: 'ct-runtime', status: m.execution.status }, modelRuntimeTelemetry: telemetry }; const input = { execution: { executionId: m.execution.id, project: m.execution.project, status: m.execution.status, startedAt: m.execution.startedAt, finishedAt: m.execution.finishedAt }, evidence }; if (semanticPath) input.semantic = await readBoundedJson(semanticPath, MAX_RESULT); const r = await mod.digestAndAppend(observerStore, input); if (r.result.status === 'duplicate') { const existing = await readBoundedJson(observerStore.recordPath(m.execution.id), MAX_RESULT); if (JSON.stringify(existing.provenance) !== JSON.stringify(r.digest.provenance)) throw new Error('immutable Observer provenance conflict'); } if (input.semantic) { await store.updateManifest(m.execution.id, { observer: { state: 'observed', observedAt: now() } }); out.push({ executionId: m.execution.id, status: 'observed' }); } else out.push({ executionId: m.execution.id, status: 'processed' }); } catch (error) { await store.event('observer_pending', { executionId: m.execution.id, error: error.message }); out.push({ executionId: m.execution.id, status: 'semantic-analysis-pending' }); } } return out; }
