/* One bounded unit per wake. Durable continuation identity is authoritative. */
function runWakeAttempt(context) {
  context=context||{}; var started=Date.now(), props=PropertiesService.getScriptProperties(), budget=CT_GAS.budgetMs(props.getProperty('CT_GAS_BUDGET_MS')), clock=CT_GAS.clock(started,budget), state=CT_GAS_STATE;
  var supplied=context.work_order_id, wakeId=context.wake_id, parentExecutionId=context.execution_id, executionId=context.physical_execution_id || context.execution_id, physicalExecutionId=context.physical_execution_id || '', suppliedContinuation=context.continuation_id;
  function op(name,cost,fn) { var r=CT_GAS.runGuard(clock,name,cost,fn); if (r&&r.status==='preempted') return r; if (!clock.canStart(0)) return {status:'preempted',operation:name,reason:'post-operation-unsafe'}; return r; }
  function wakeFor(id,base,reason) { return {time:new Date(Date.now()+1000).toISOString(),reason:reason==='model-deferred'?'model-deferred':'checkpoint',priority:'normal',project:base.project||'default',work_order_id:supplied,execution_id:executionId,continuation_id:id,launch:base.launch_context||{},resume:base.resume_context||{}}; }
  function checkpoint(reason,base) {
    var began=Date.now(), emergency=CT_GAS.emergencyClock(began), p=base||{}, nextId=CT_GAS.id('continuation',{work_order_id:supplied,execution_id:executionId,wake_id:wakeId,reason:reason,next_operation:p.next_operation||'resume'}), c;
    try {
      var result=CT_GAS.runGuard(emergency,'emergency-checkpoint',CT_GAS.OPERATION_BUDGETS.checkpoint,function () {
         c=CT_GAS.continuation({goal:p.goal||'Continue bounded work',completed:p.completed||[],decisions:p.decisions||[],evidence:p.evidence||[],provenance:p.provenance||[],outstanding:p.outstanding||[p.step||'next'],next_operation:p.next_operation||'resume',reason:reason,resumed_from:executionId,physical_execution_count:Number(p.physical_execution_count||1),attempt:Number(p.attempt||0),work_order_id:supplied,execution_id:executionId,wake_id:wakeId,continuation_id:nextId,wait_condition:p.wait_condition||'',launch_context:p.launch_context||context.launch||{},resume_context:p.resume_context||context.resume||{}});
        state.continuation(c);
        var current=state.get('work_orders',supplied), target=reason==='model-deferred'?'deferred':'checkpointed';
        if (current && current.lifecycle!==target) state.update('work_orders',supplied,{lifecycle:target,payload:c});
        else if (current) state.update('work_orders',supplied,{payload:c});
        return {status:'persisted',continuation_id:nextId};
      });
      if (result.status==='preempted') throw new Error('emergency-budget-exhausted');
      var scheduled; try { scheduled=requestNextWake(wakeFor(nextId,p,reason)); } catch (_) { throw new Error('continuation-wake-not-scheduled'); }
      if (!scheduled || !scheduled.id) throw new Error('continuation-wake-not-scheduled');
      try { state.telemetry({execution_id:executionId,physical_execution_id:physicalExecutionId,work_order_id:supplied,wake_id:wakeId,continuation_id:nextId,operation:'checkpoint',continuation_reason:reason,checkpoint_count:1,checkpoint_latency_ms:Date.now()-began,physical_execution_count:Number(p.physical_execution_count||1),budget_ms:budget,actual_duration_ms:Date.now()-started,general_compute_requested:false}); } catch (_) {}
      return {status:'checkpointed',reason:reason,continuation_id:nextId,work_order_id:supplied,execution_id:executionId,wake_id:wakeId};
    } catch (_) { try { state.event('wake_interrupted',{execution_id:executionId,work_order_id:supplied,wake_id:wakeId,continuation_id:c&&c.continuation_id||suppliedContinuation,operation:'checkpoint',reason:'incomplete-checkpoint-recoverable',general_compute_requested:false}); } catch (__) {} return {status:'interrupted',reason:'incomplete-checkpoint-recoverable',work_order_id:supplied,execution_id:executionId,wake_id:wakeId}; }
  }
  if (!supplied||!wakeId||!executionId||!suppliedContinuation) return {status:'interrupted',reason:'missing-wake-identity'};
   var work=op('state-read-work-order',CT_GAS.OPERATION_BUDGETS.stateRead,function () { return state.get('work_orders',supplied); }); if (work&&work.status==='preempted') return checkpoint('before-work-order-read'); if (work && work.lifecycle === 'completed') return {status:'duplicate',work_order_id:supplied,execution_id:executionId,wake_id:wakeId,continuation_id:suppliedContinuation};
  var latest=op('state-read-continuation',CT_GAS.OPERATION_BUDGETS.stateRead,function () { return state.latestContinuation(supplied); }); if (latest&&latest.status==='preempted') return checkpoint('before-continuation-read',(work&&work.payload)||{});
  var p=work&&work.payload||{}, launch=CT_GAS.context((latest&&latest.launch_context)||p.launch_context||context.launch), resume=CT_GAS.context((latest&&latest.resume_context)||p.resume_context||context.resume);
  if (!work) { var model=launch.model||p.model; if (!model) return {status:'interrupted',reason:'selected-model-missing'}; CT_GAS.freeModel(model); var boot=op('state-bootstrap',CT_GAS.OPERATION_BUDGETS.stateWrite,function () { return state.create('work_orders',{id:supplied,lifecycle:'requested',payload:{work_order_id:supplied,goal:'Continue bounded work',step:'A',model:model,physical_execution_count:1,launch_context:launch,resume_context:resume}}); }); if (boot.status==='preempted') return checkpoint('before-bootstrap',p); work=boot; p=work.payload||p; }
   if (latest) { if (latest.work_order_id!==supplied || latest.execution_id!==parentExecutionId || latest.continuation_id!==suppliedContinuation) return {status:'deferred',reason:'continuation-identity-mismatch'}; p=Object.assign({},p,latest); launch=CT_GAS.context(latest.launch_context); resume=CT_GAS.context(latest.resume_context); }
  var selected=launch.model||p.model; if (!selected) return checkpoint('selected-model-missing',Object.assign({},p,{launch_context:launch,resume_context:resume})); CT_GAS.freeModel(selected);
   var count=state.physicalExecutionCount(supplied);
  if (!latest) { var bootContinuation=op('continuation-bootstrap',CT_GAS.OPERATION_BUDGETS.stateWrite,function () { return state.continuation(CT_GAS.continuation({goal:p.goal||'Continue bounded work',completed:p.completed||[],decisions:p.decisions||[],evidence:p.evidence||[],provenance:p.provenance||[],outstanding:p.outstanding||['A'],next_operation:'model',reason:'bootstrap',resumed_from:executionId,physical_execution_count:count,work_order_id:supplied,execution_id:executionId,wake_id:wakeId,continuation_id:suppliedContinuation,launch_context:launch,resume_context:resume})); }); if (bootContinuation.status==='preempted') return checkpoint('before-continuation-bootstrap',Object.assign({},p,{launch_context:launch,resume_context:resume})); }
  if (p.evidence_ref && p.next_operation==='verify') { var verified=op('drive-verify',CT_GAS.OPERATION_BUDGETS.drive,function () { return CT_GAS_EVIDENCE.verifyExisting(p.evidence_ref.drive_file_id,p.evidence_ref.sha256,clock); }); if (verified.status==='preempted') return checkpoint('before-verification',p); var observed=CT_GAS_OBSERVER.pass({clock:clock,execution_id:executionId,physical_execution_id:physicalExecutionId,work_order_id:supplied,wake_id:wakeId,continuation_id:suppliedContinuation,evidence:verified}); if (observed.status==='preempted') return checkpoint('before-observer',p); try { state.update('work_orders',supplied,{lifecycle:'completed',payload:{step:'B',verified:verified.drive_file_id,physical_execution_count:count}}); } catch (_) { return checkpoint('completion-mutation-failed',p); } try { state.telemetry({execution_id:executionId,physical_execution_id:physicalExecutionId,work_order_id:supplied,wake_id:wakeId,continuation_id:suppliedContinuation,operation:'verification',verified:true,budget_ms:budget,actual_duration_ms:Date.now()-started,physical_execution_count:count,general_compute_requested:false}); } catch (_) {} return {status:'complete',step:'B',verified:true}; }
  var running=op('state-mutation-running',CT_GAS.OPERATION_BUDGETS.stateWrite,function () { return state.update('work_orders',supplied,{lifecycle:'running',payload:{physical_execution_count:count,model:selected,launch_context:launch,resume_context:resume}}); }); if (running.status==='preempted') return checkpoint('before-running',p);
   var result=executeAgent({execution_id:executionId,physical_execution_id:physicalExecutionId,work_order_id:supplied,wake_id:wakeId,continuation_id:suppliedContinuation,project:p.project||'default',model:selected,verify_price:true,maxTurns:1,maxTokens:256,messages:[{role:'user',content:'Return a bounded factual acknowledgement.'}],deadline:Number(p.retry_deadline_ms||Date.now()+3600000),attempt:Number(p.attempt||0),clock:clock,requiredMs:CT_GAS.OPERATION_BUDGETS.model,launch:launch,resume:resume});
   if (result.status==='preempted') return checkpoint(result.reason,Object.assign({},p,{model:selected,launch_context:launch,resume_context:resume})); if (result.status==='deferred') return checkpoint('model-deferred',Object.assign({},p,{model:selected,attempt:result.attempt||Number(p.attempt||0),retry_deadline_ms:Number(p.retry_deadline_ms||Date.now()+3600000),next_operation:'model',launch_context:launch,resume_context:resume}));
  var evidence=op('drive-put-verify',CT_GAS.OPERATION_BUDGETS.drive,function () { return storeEvidence({execution_id:executionId,kind:'executions',content:result.output,mimeType:'text/plain',provenance:{work_order_id:supplied,step:'A',model:selected},clock:clock}); }); if (evidence.status==='preempted') return checkpoint('before-evidence',Object.assign({},p,{model:selected,launch_context:launch,resume_context:resume}));
   var progress=Object.assign({},p,{goal:p.goal||'Continue bounded work',step:'A',model:selected,requested_model:result.requested_model||selected,actual_model:result.model||selected,evidence:[evidence.drive_file_id],evidence_ref:evidence,evidence_hash:evidence.sha256,completed:['A model'],provenance:['Drive evidence '+evidence.sha256],physical_execution_count:count,next_operation:'verify',launch_context:launch,resume_context:resume});
  try { state.update('work_orders',supplied,{lifecycle:'checkpointed',payload:progress}); } catch (_) { return checkpoint('evidence-progress-write-failed',progress); }
  var progressId=CT_GAS.id('continuation',{work_order_id:supplied,execution_id:executionId,wake_id:wakeId,next_operation:'verify',evidence:evidence});
  try { state.continuation(CT_GAS.continuation({goal:progress.goal,completed:progress.completed,decisions:progress.decisions,evidence:progress.evidence,provenance:progress.provenance,outstanding:['B'],next_operation:'verify',reason:'evidence-persisted',resumed_from:executionId,physical_execution_count:count,work_order_id:supplied,execution_id:executionId,wake_id:wakeId,continuation_id:progressId,launch_context:launch,resume_context:resume})); } catch (_) { return checkpoint('evidence-continuation-write-failed',progress); }
  var obs=CT_GAS_OBSERVER.pass({clock:clock,execution_id:executionId,work_order_id:supplied,wake_id:wakeId,continuation_id:progressId,evidence:evidence}); if (obs.status==='preempted') return checkpoint('before-observer',Object.assign({},progress,{continuation_id:progressId}));
  try { state.telemetry({execution_id:executionId,physical_execution_id:physicalExecutionId,work_order_id:supplied,wake_id:wakeId,continuation_id:progressId,model:selected,requested_model:result.requested_model||selected,canonical_model:CT_GAS.canonicalModel(selected),actual_model:result.model||selected,model_invocation_count:1,turns:1,elapsed_ms:result.elapsed_ms,actual_duration_ms:Date.now()-started,budget_ms:budget,physical_execution_count:count,general_compute_requested:false}); } catch (_) {}
  try { var scheduled=requestNextWake(wakeFor(progressId,progress,'checkpoint')); if (!scheduled||!scheduled.id) throw new Error('wake-not-scheduled'); } catch (_) { return {status:'interrupted',reason:'checkpointed-without-continuation-wake',work_order_id:supplied,execution_id:executionId}; }
  return {status:'checkpointed',step:'A',evidence:evidence};
}
 function runWakeInternal(context) {
   context=context||{};
   var started=Date.now(), record=null, result;
   try {
     record=CT_GAS_STATE.executionStart({work_order_id:context.work_order_id,parent_execution_id:context.execution_id,wake_id:context.wake_id,continuation_id:context.continuation_id,reconstruction_source:context.reconstruction_source||'durable-sheets'});
     result=runWakeAttempt(Object.assign({},context,{physical_execution_id:record.id}));
     return result;
   } finally {
     if (record) {
       var status=result&&result.status, lifecycle=status==='complete'?'completed':status==='checkpointed'?'checkpointed':status==='deferred'?'deferred':status==='interrupted'?'preempted':'failed';
       try { CT_GAS_STATE.executionFinish(record.id,{lifecycle:lifecycle,completion_reason:result&&result.reason||status||'exception',actual_duration_ms:Date.now()-started,next_physical_execution_id:result&&result.continuation_id||'',model_invocation_count:status==='checkpointed'&&result.step==='A'?1:0,checkpoint_count:status==='checkpointed'?1:0,evidence_refs:result&&result.evidence&&result.evidence.drive_file_id?[result.evidence.drive_file_id]:[]}); } catch (_) {}
     }
   }
 }
 function wake(context) { return runWake(context); }
function runWake(context) { try { return runWakeInternal(context); } catch (e) { try { CT_GAS_STATE.event('wake_interrupted',{execution_id:context&&context.execution_id,work_order_id:context&&context.work_order_id,wake_id:context&&context.wake_id,continuation_id:context&&context.continuation_id,reason:'runtime-interruption',error:CT_GAS.bound(e.message||e,240),general_compute_requested:false}); } catch (_) {} return {status:'deferred',reason:'runtime-interruption'}; } }
