/* Narrow, separately authenticated self-deployment capability. */
var CT_GAS_DEPLOY = (function () {
  var API = 'https://script.googleapis.com/v1';
  var MAX_FILES = 64;
  var MAX_FILE_BYTES = 262144;
  var MAX_BUNDLE_BYTES = 2097152;
  var MAX_RESPONSE_BYTES = 4194304;
  var MAX_NONCES = 256;
  var MAX_REQUEST_FENCES = 256;
  var MAX_VERSIONS = 200;
  var NONCE_TTL_MS = 10 * 60 * 1000;
  var CLOCK_SKEW_SEC = 300;
  var NONCE_PREFIX = 'CT_GAS_DEPLOY_NONCE_';
  var REQUEST_PREFIX = 'CT_GAS_DEPLOY_REQUEST_';
  function props() { return PropertiesService.getScriptProperties(); }
  function equal(a,b){a=String(a||'');b=String(b||'');var n=Math.max(a.length,b.length),diff=a.length^b.length;for(var i=0;i<n;i++)diff|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return diff===0;}
  function hex(bytes){return bytes.map(function(b){return ('0'+(b<0?b+256:b).toString(16)).slice(-2);}).join('');}
  function digest(value){return hex(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value,Utilities.Charset.UTF_8));}
  function hmac(value,secret){return hex(Utilities.computeHmacSha256Signature(value,secret,Utilities.Charset.UTF_8));}
  function bytes(value){return Utilities.newBlob(String(value),'text/plain').getBytes().length;}
  function fail(message){throw new Error('deploy-'+message);}
  function json(value){return JSON.stringify(value);}
  function path(id){return encodeURIComponent(String(id));}
  function api(method,url,body){var options={method:method,headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken()},muteHttpExceptions:true};if(body!==undefined){options.contentType='application/json';options.payload=json(body);}var response=UrlFetchApp.fetch(url,options),text=response.getContentText();if(bytes(text)>MAX_RESPONSE_BYTES)fail('google-response-too-large');var code=response.getResponseCode();if(code<200||code>=300){var detail={};try{detail=JSON.parse(text);}catch(_){}throw new Error('deploy-google-api-'+code+' '+String(detail.error&&detail.error.message||'').slice(0,300));}try{return JSON.parse(text);}catch(_){fail('google-response-invalid-json');}}
  function ownScriptId(){return String(ScriptApp.getScriptId());}
  function configuredDeploymentId(){return String(props().getProperty('CT_GAS_DEPLOYMENT_ID')||'');}
  function deployment(scriptId,deploymentId){return api('get',API+'/projects/'+path(scriptId)+'/deployments/'+path(deploymentId));}
  function deploymentConfig(dep){var config=dep&&dep.deploymentConfig;if(!config||typeof config!=='object')fail('deployment-config-missing');if(String(config.scriptId||'')!==String(ownScriptId()))fail('deployment-config-script-mismatch');if(config.manifestFileName===undefined||config.description===undefined)fail('deployment-config-incomplete');return config;}
  function deploymentVersion(dep){var config=deploymentConfig(dep),value=String(config.versionNumber||'');if(!value)fail('deployment-version-missing');return value;}
  function content(scriptId,versionNumber){var url=API+'/projects/'+path(scriptId)+'/content';if(versionNumber!==undefined&&versionNumber!==null)url+='?versionNumber='+encodeURIComponent(String(versionNumber));return api('get',url);}
  function version(scriptId,versionNumber){return api('get',API+'/projects/'+path(scriptId)+'/versions/'+path(versionNumber));}
  function versions(scriptId,pageToken){var url=API+'/projects/'+path(scriptId)+'/versions?pageSize=200';if(pageToken)url+='&pageToken='+encodeURIComponent(String(pageToken));return api('get',url);}
  function allVersions(scriptId){var out=[],token='';do{var page=versions(scriptId,token);out=out.concat(parseVersions(page));token=String(page&&page.nextPageToken||'');if(out.length>MAX_VERSIONS)fail('version-capacity-invalid');}while(token);return out;}
  function versionCapacity(scriptId){var used=allVersions(scriptId).length;return {used:used,max:MAX_VERSIONS,remaining:Math.max(0,MAX_VERSIONS-used),status:used>=MAX_VERSIONS?'exhausted':(used>=MAX_VERSIONS-10?'low':'ready')};}
  function canonicalName(name){if(name==='appsscript.json'||name==='appsscript')return 'appsscript';return name.replace(/\.(?:js|mjs|html)$/i,'');}
  function normalizeFiles(files){if(!Array.isArray(files)||!files.length||files.length>MAX_FILES)fail('invalid-file-count');var seen={},canonical={},manifest=0,out=[];files.forEach(function(file){if(!file||typeof file!=='object'||typeof file.name!=='string'||typeof file.source!=='string'||typeof file.type!=='string')fail('invalid-file');if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(file.name)||file.name.indexOf('..')>=0||file.name.indexOf('/')>=0||file.name.indexOf('\\')>=0)fail('invalid-file-name');if(seen[file.name])fail('duplicate-file');seen[file.name]=true;if(['SERVER_JS','HTML','JSON'].indexOf(file.type)<0)fail('invalid-file-type');var name=canonicalName(file.name);if(name==='appsscript'){if(file.type!=='JSON')fail('invalid-manifest-type');manifest++;}else if(file.type==='JSON')fail('unexpected-json-file');if(canonical[name])fail('duplicate-canonical-file');canonical[name]=true;if(bytes(file.source)>MAX_FILE_BYTES)fail('file-too-large');out.push({name:name,type:file.type,source:file.source});});if(manifest!==1)fail('manifest-required');out.sort(function(a,b){return a.name<b.name?-1:a.name>b.name?1:0;});if(bytes(json(out))>MAX_BUNDLE_BYTES)fail('bundle-too-large');return out;}
  function bundleHash(files){return digest(json(normalizeFiles(files)));}
  function contentHash(project){return bundleHash(project.files||[]);}
  function marker(description){var text=String(description||''),out={};text.split(/\s+/).forEach(function(part){var i=part.indexOf('=');if(i>0)out[part.slice(0,i)]=part.slice(i+1);});return text.indexOf('ct-runtime-deploy')>=0?out:null;}
  function markerDescription(request){return 'ct-runtime-deploy request_id='+request.deployment_request_id+' commit='+request.commit_sha+' bundle='+request.bundle_hash;}
  function verifyMarker(v,request){var m=marker(v&&v.description);return !!m&&m.request_id===request.deployment_request_id&&m.commit===request.commit_sha&&m.bundle===request.bundle_hash;}
  function parseVersions(result){return Array.isArray(result&&result.versions)?result.versions:[];}
  function findRequestMarker(scriptId,request){var found=null;allVersions(scriptId).forEach(function(v){var m=marker(v&&v.description);if(m&&m.request_id===request.deployment_request_id){if(m.commit!==request.commit_sha||m.bundle!==request.bundle_hash)fail('request-marker-conflict');found=v;}});return found;}
  function recoverVersion(scriptId,request){var matches=allVersions(scriptId).filter(function(v){return verifyMarker(v,request);});if(!matches.length)return null;matches.sort(function(a,b){return Number(b.versionNumber)-Number(a.versionNumber);});return matches[0];}
  function nonceHash(nonce){return digest(String(nonce));}
  function reserveNonce(nonce){var lock=LockService.getScriptLock();lock.waitLock(10000);try{var now=Date.now(),hash=nonceHash(nonce),prefix=NONCE_PREFIX,all=props().getProperties(),active=[];Object.keys(all).forEach(function(key){if(key.indexOf(prefix)!==0)return;var expiresAt=Number(all[key]);if(!Number.isFinite(expiresAt)||expiresAt<=now){props().deleteProperty(key);return;}active.push({key:key,expiresAt:expiresAt});});var key=prefix+hash;var current=props().getProperty(key);if(current!==null&&Number(current)>now)fail('nonce-replay');if(active.length>=MAX_NONCES)fail('nonce-capacity');props().setProperty(key,String(now+NONCE_TTL_MS));}finally{lock.releaseLock();}}
  function requestFence(request){var key=REQUEST_PREFIX+digest(request.deployment_request_id).slice(0,48),all=props().getProperties(),now=Date.now(),entries=[];Object.keys(all).forEach(function(candidate){if(candidate.indexOf(REQUEST_PREFIX)!==0)return;var value;try{value=JSON.parse(all[candidate]);}catch(_){props().deleteProperty(candidate);return;}if(!value||!Number.isFinite(Number(value.createdAt))){props().deleteProperty(candidate);return;}entries.push({key:candidate,createdAt:Number(value.createdAt)});});var prior=props().getProperty(key),identity=request.commit_sha+':'+request.bundle_hash;if(prior){var parsed;try{parsed=JSON.parse(prior);}catch(_){parsed=null;}if(parsed&&parsed.identity!==identity)fail('request-conflict');}if(!prior&&entries.length>=MAX_REQUEST_FENCES)fail('request-fence-capacity');props().setProperty(key,json({identity:identity,createdAt:now}));}
  function releaseRequestFence(request){var key=REQUEST_PREFIX+digest(request.deployment_request_id).slice(0,48);props().deleteProperty(key);}
  function authenticate(raw,query){var timestamp=String(query.timestamp||''),nonce=String(query.nonce||''),signature=String(query.signature||''),secret=props().getProperty('CT_GAS_DEPLOY_HMAC_SECRET');if(!secret||!timestamp||!nonce||!signature)fail('authentication-missing');var seconds=Number(timestamp),now=Math.floor(Date.now()/1000);if(!/^\d+$/.test(timestamp)||!Number.isSafeInteger(seconds)||Math.abs(now-seconds)>CLOCK_SKEW_SEC)fail('authentication-skew');var request;try{request=JSON.parse(raw);}catch(_){fail('invalid-json');}if(request.operation!=='self-deploy'&&request.operation!=='self-deploy-plan'&&request.operation!=='self-deploy-qualify')fail('operation-not-allowed');var bodyHash=digest(raw),signed=[request.operation,timestamp,nonce,request.deployment_request_id||'',request.script_id||'',request.deployment_id||'',request.commit_sha||'',request.bundle_hash||'',bodyHash].join('\n');if(!equal(signature,hmac(signed,secret)))fail('authentication-signature');reserveNonce(nonce);return request;}
  function validateRequest(request){if(!/^[0-9a-f]{40}$/.test(String(request.commit_sha||'')))fail('invalid-commit');if(!/^[0-9a-f]{64}$/.test(String(request.bundle_hash||'')))fail('invalid-bundle-hash');if(!/^[A-Za-z0-9][A-Za-z0-9._-]{7,127}$/.test(String(request.deployment_request_id||'')))fail('invalid-request-id');if(!/^[A-Za-z0-9][A-Za-z0-9._-]{7,127}$/.test(String(request.deployment_id||'')))fail('invalid-deployment-id');if(!/^[A-Za-z0-9_-]{20,100}$/.test(String(request.script_id||'')))fail('invalid-script-id');}
  function liveState(request){if(ownScriptId()!==request.script_id)fail('script-id-mismatch');var configured=configuredDeploymentId();if(!configured||configured!==request.deployment_id)fail('deployment-id-mismatch');var dep=deployment(request.script_id,request.deployment_id),versionNumber=deploymentVersion(dep),liveContent=content(request.script_id,versionNumber);return {deployment:dep,versionNumber:versionNumber,bundleHash:contentHash(liveContent),content:liveContent};}
  function expectedFence(request,live){if(String(request.expected_live_version||'')!==String(live.versionNumber)||String(request.expected_live_bundle_hash||'')!==String(live.bundleHash))fail('live-state-conflict');}
  function head(request){var value=content(request.script_id);return {content:value,bundleHash:contentHash(value)};}
  function updateHead(request,files){return api('put',API+'/projects/'+path(request.script_id)+'/content',{files:files});}
  function createVersion(request){return api('post',API+'/projects/'+path(request.script_id)+'/versions',{description:markerDescription(request)});}
  function updateDeployment(request,live,versionNumber){var config=JSON.parse(JSON.stringify(deploymentConfig(live.deployment)));config.versionNumber=Number(versionNumber);return api('put',API+'/projects/'+path(request.script_id)+'/deployments/'+path(request.deployment_id),{deploymentConfig:config});}
  function qualify(request){if(ownScriptId()!==request.script_id)fail('script-id-mismatch');var value=content(request.script_id);return {status:'qualified',scriptId:request.script_id,headBundleHash:contentHash(value),fileCount:(value.files||[]).length};}
  function plan(request){var live=liveState(request),h=head(request),capacity=versionCapacity(request.script_id);return {status:'planned',scriptId:request.script_id,deploymentId:request.deployment_id,liveVersion:live.versionNumber,liveBundleHash:live.bundleHash,headBundleHash:h.bundleHash,versionCapacity:capacity};}
  function createOrRecoverVersion(request){try{return createVersion(request);}catch(error){var recovered=recoverVersion(request.script_id,request);if(recovered)return recovered;throw error;}}
  function updateDeploymentConverge(request,live,versionNumber){try{return updateDeployment(request,live,versionNumber);}catch(error){var observed=deployment(request.script_id,request.deployment_id),observedVersion=deploymentVersion(observed);if(observedVersion===String(versionNumber))return observed;throw error;}}
  function deploy(request,files){validateRequest(request);var normalized=normalizeFiles(files),actualHash=bundleHash(normalized);if(actualHash!==request.bundle_hash)fail('bundle-hash-mismatch');var lock=LockService.getScriptLock();lock.waitLock(30000);try{var markerVersion=findRequestMarker(request.script_id,request),live=liveState(request);if(markerVersion&&String(live.versionNumber)===String(markerVersion.versionNumber)){var deployed=content(request.script_id,live.versionNumber);if(contentHash(deployed)!==request.bundle_hash)fail('marker-content-mismatch');releaseRequestFence(request);return {status:'verified',requestId:request.deployment_request_id,versionNumber:live.versionNumber,deploymentId:request.deployment_id,bundleHash:request.bundle_hash};}expectedFence(request,live);var h=head(request);if(h.bundleHash!==request.expected_live_bundle_hash&&h.bundleHash!==request.bundle_hash)fail('head-state-conflict');requestFence(request);if(h.bundleHash!==request.bundle_hash)updateHead(request,normalized);var recovered=markerVersion||recoverVersion(request.script_id,request),v=recovered||createOrRecoverVersion(request),versionNumber=String(v.versionNumber||'');if(!versionNumber)fail('version-number-missing');if(String(live.versionNumber)!==versionNumber)updateDeploymentConverge(request,live,versionNumber);var finalDep=deployment(request.script_id,request.deployment_id),finalVersion=deploymentVersion(finalDep);if(finalVersion!==versionNumber)fail('readback-deployment-mismatch');var finalContent=content(request.script_id,finalVersion),finalHash=contentHash(finalContent);if(finalHash!==request.bundle_hash)fail('readback-bundle-mismatch');var finalVersionInfo=version(request.script_id,finalVersion);if(!verifyMarker(finalVersionInfo,request))fail('readback-marker-mismatch');var finalHead=head(request);if(finalHead.bundleHash!==request.bundle_hash)fail('readback-head-mismatch');releaseRequestFence(request);return {status:'verified',requestId:request.deployment_request_id,versionNumber:finalVersion,deploymentId:request.deployment_id,bundleHash:finalHash,headBundleHash:finalHead.bundleHash,fileCount:(finalContent.files||[]).length};}finally{lock.releaseLock();}}
  return {authenticate:authenticate,qualify:qualify,plan:plan,deploy:deploy,bounds:{maxFiles:MAX_FILES,maxFileBytes:MAX_FILE_BYTES,maxBundleBytes:MAX_BUNDLE_BYTES,maxNonces:MAX_NONCES,maxRequestFences:MAX_REQUEST_FENCES,maxVersions:MAX_VERSIONS}};
}());
function selfDeployRejectionReason(error){var message=String(error&&error.message||'');return message.indexOf('deploy-')===0?message:'deploy-internal-error';}
function deploymentIdFromWebAppUrl(url){var value=String(url||'').trim(),match=value.match(/^https:\/\/script\.google\.com\/macros\/s\/([A-Za-z0-9_-]+)\/(?:exec|dev)\/?$/);return match?match[1]:'';}
function bootstrapSelfDeploymentPin(webAppUrl){var source=webAppUrl===undefined?ScriptApp.getService().getUrl():webAppUrl;var observedUrl=String(source||'');var id=deploymentIdFromWebAppUrl(observedUrl);if(!id)return {status:'invalid-url',reason:'deploy-bootstrap-url-invalid',observedUrl:observedUrl};var existing=String(PropertiesService.getScriptProperties().getProperty('CT_GAS_DEPLOYMENT_ID')||'');if(existing&&existing!==id)throw new Error('deploy-bootstrap-pin-conflict');PropertiesService.getScriptProperties().setProperty('CT_GAS_DEPLOYMENT_ID',id);return {status:existing?'already-configured':'configured',deploymentId:id,observedUrl:observedUrl};}
