/* GAS is an advisory consumer. Node owns the canonical advisory and Neon owns coordination. */
var CT_GAS_FEDERATION = (function () {
  var paths={pending:'/rpc/federation_pending_advisories',take:'/rpc/federation_take_for_gas',checkpoint:'/rpc/federation_checkpoint_for_gas'};
  function props(){return PropertiesService.getScriptProperties();}
  function identityToken(){var token=ScriptApp.getIdentityToken();if(!token)throw new Error('GAS identity token unavailable');return token;}
  function digest(value){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value,Utilities.Charset.UTF_8).map(function(b){return ('0'+(b<0?b+256:b).toString(16)).slice(-2);}).join('');}
  function rpc(name,value,clock){if(!paths[name])throw new Error('unsupported federation RPC');var base=props().getProperty('CT_GAS_FEDERATION_DATA_API_URL');if(!base)throw new Error('federation Data API URL is required');var token=identityToken(),response=UrlFetchApp.fetch(base+paths[name],{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+token},payload:JSON.stringify(value||{}),muteHttpExceptions:true}),code=response.getResponseCode();if(code<200||code>=300){if(code===400)throw new Error('federation RPC invalid-request');if(code===401)throw new Error('federation RPC unauthorized');if(code===403){var detail={},claims={};try{detail=JSON.parse(response.getContentText());}catch(_){}try{claims=JSON.parse(Utilities.newBlob(Utilities.base64DecodeWebSafe(token.split('.')[1])).getDataAsString());}catch(_){}var machine=String(detail.code||'unknown'),message=String(detail.message||''),kind=/function/i.test(message)?'function':/schema/i.test(message)?'schema':/table|relation/i.test(message)?'table':/role/i.test(message)?'role':'other',role=/^[A-Za-z0-9_-]{1,32}$/.test(String(claims.role||''))?String(claims.role):'none';throw new Error('federation RPC forbidden-'+kind+' '+(/^[A-Z0-9_]{1,32}$/.test(machine)?machine:'unknown')+' role-'+role);}if(code===404)throw new Error('federation RPC missing-function');throw new Error('federation RPC unavailable');}return JSON.parse(CT_GAS.bound(response.getContentText(),CT_GAS.MAX_PAYLOAD));}
  function equal(a,b){a=String(a||'');b=String(b||'');var n=Math.max(a.length,b.length),diff=a.length^b.length;for(var i=0;i<n;i++)diff|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return diff===0;}
  function hmac(message,secret){return Utilities.computeHmacSha256Signature(message,secret,Utilities.Charset.UTF_8).map(function(b){return ('0'+(b<0?b+256:b).toString(16)).slice(-2);}).join('');}
  function verify(e){var raw=String(e&&e.postData&&e.postData.contents||''), query=e&&e.parameter||{}, timestamp=String(query.timestamp||''), signature=String(query.signature||''), secret=props().getProperty('CT_GAS_FEDERATION_HMAC_SECRET');if(!secret||!timestamp||!signature)throw new Error('missing federation authentication');var seconds=Number(timestamp),now=Math.floor(Date.now()/1000);if(!/^\d+$/.test(timestamp)||!Number.isSafeInteger(seconds)||Math.abs(now-seconds)>300)throw new Error('federation authentication skew');if(!equal(signature,hmac(timestamp+'.'+raw,secret)))throw new Error('invalid federation signature');if(raw.length>CT_GAS_FEDERATION_MAX_BODY)throw new Error('advisory body exceeds bound');var advisory=JSON.parse(raw);if(advisory.operation==='evidence-ingest')return advisory;if(advisory.schema!=='celestan-gas-federation-advisory-v1'||advisory.version!==1||!advisory.nonce||!advisory.workOrderId||!advisory.handoffId||!advisory.checkpointDigest)throw new Error('invalid federation advisory');if(Date.parse(advisory.expiresAt)<=Date.now()||Date.parse(advisory.issuedAt)>Date.now())throw new Error('expired federation advisory');return advisory;}
   function runAdvisory(input,clock){var advisory=input.advisory||input,advisoryText=input.advisoryText||CT_GAS.json(advisory),bodyDigest=input.bodyDigest||digest(advisoryText);var taken=rpc('take',{p_advisory_text:advisoryText,p_body_digest:bodyDigest},clock);if(!taken||taken.status!=='taken')return {status:taken&&taken.status||'rejected',nonce:advisory.nonce};var physical=CT_GAS_STATE.executionStart({work_order_id:taken.workOrderId,parent_execution_id:taken.executionId,wake_id:'federation-'+advisory.nonce,continuation_id:'federation-'+advisory.nonce,reconstruction_source:'neon-federation'}), evidence=[];
    try { var ref=CT_GAS_EVIDENCE.put({execution_id:physical.id,kind:'execution',content:'CT-Runtime GAS bounded federation evidence\n'+advisory.nonce,mimeType:'text/plain',provenance:{source:'gas-federation',advisory:advisory.nonce},clock:clock}); if(ref&&ref.drive_file_id)evidence.push(ref); } catch (_) {}
    var continuation=CT_GAS_STATE.continuation(CT_GAS.continuation({goal:'Federated continuation',completed:['Neon advisory reconstructed','GAS physical execution started'],decisions:['No model call required for bounded federation transport'],evidence:evidence.map(function(x){return x.drive_file_id||x.sha256;}),provenance:['Neon advisory '+advisory.nonce],outstanding:[],next_operation:'interactive-reconstruction',reason:'federation-advisory',resumed_from:physical.id,physical_execution_count:CT_GAS_STATE.physicalExecutionCount(taken.workOrderId),work_order_id:taken.workOrderId,execution_id:physical.id,wake_id:'federation-'+advisory.nonce,continuation_id:'federation-'+advisory.nonce,launch_context:{provider:'gas'},resume_context:{source:'neon-federation'}}));
      var checkpoint={schema:'celestan-gas-checkpoint-v1',version:1,workOrderId:taken.workOrderId,executionId:taken.executionId,physicalExecutionId:physical.id,continuationId:'federation-'+advisory.nonce,advisoryNonce:advisory.nonce,evidence:evidence,completed:['bounded GAS transport execution','local continuation'].concat(evidence.length?['transport evidence persisted']:[]),objectiveExecuted:false,objectiveCompleted:false,nextOperation:'interactive-reconstruction',reconstructedAt:new Date().toISOString()};
     var checkpointText=CT_GAS.json(checkpoint),checkpointDigest=digest(checkpointText),result;try { result=rpc('checkpoint',{p_advisory_text:advisoryText,p_body_digest:bodyDigest,p_checkpoint_text:checkpointText,p_checkpoint_digest:checkpointDigest,p_fence:taken.fence},clock);if(!result||result.status!=='checkpointed')throw new Error('federation checkpoint rejected'); } catch (error) { try { CT_GAS_STATE.executionFinish(physical.id,{lifecycle:'deferred',completion_reason:'canonical-checkpoint-failed',checkpoint_count:1,checkpoint_digest:checkpointDigest,continuation_id:'federation-'+advisory.nonce,evidence_refs:evidence}); } catch (_) {} throw error; } CT_GAS_STATE.executionFinish(physical.id,{lifecycle:'completed',checkpoint_count:1,checkpoint_digest:checkpointDigest,continuation_id:'federation-'+advisory.nonce,evidence_refs:evidence});return {status:'checkpointed',nonce:advisory.nonce,executionId:taken.executionId,physicalExecutionId:physical.id,checkpointDigest:checkpointDigest};
  }
  function ingest(input,clock){var value=input.evidence||input;if(!value||value.schema!=='celestan-execution-evidence-v1'||value.version!==1||!value.evidenceId||!value.physicalExecutionId||!value.contentHash)throw new Error('invalid execution evidence');var copy={};Object.keys(value).forEach(function(k){if(k!=='contentHash')copy[k]=value[k];});if(digest(CT_GAS.json(copy))!==value.contentHash)throw new Error('execution evidence hash mismatch');var ref=CT_GAS_EVIDENCE.put({evidence_id:value.evidenceId,physical_execution_id:value.physicalExecutionId,execution_id:value.physicalExecutionId,content:CT_GAS.json(value),schema:value.schema,mimeType:'application/json',provenance:value.provenance||{source:'authenticated-evidence-ingest'},clock:clock});return {status:'accepted',evidenceId:value.evidenceId,fileId:ref.drive_file_id,hash:ref.sha256};}
  return {consume:runAdvisory,ingest:ingest,verify:function(e){var raw=String(e&&e.postData&&e.postData.contents||''),advisory=verify(e);return {advisory:advisory,advisoryText:raw,bodyDigest:digest(raw)};},paths:paths,rpc:rpc};
}());
var CT_GAS_FEDERATION_MAX_BODY=8192;
function federationRejectionReason(error){var message=String(error&&error.message||'');var allowed=['missing federation authentication','federation authentication skew','invalid federation signature','advisory body exceeds bound','invalid federation advisory','expired federation advisory','federation Data API URL is required','federation RPC invalid-request','federation RPC unauthorized','federation RPC missing-function','federation RPC unavailable','GAS identity token unavailable','federation checkpoint rejected'];for(var i=0;i<allowed.length;i++)if(message===allowed[i])return allowed[i];if(/^federation RPC forbidden-(function|schema|table|role|other) [A-Z0-9_]{1,32} role-[A-Za-z0-9_-]{1,32}$/.test(message))return message;return 'internal-error';}
function doPost(e){try{var parsed=JSON.parse(String(e&&e.postData&&e.postData.contents||'')),auth=CT_GAS_FEDERATION.verify(e),clock=CT_GAS.clock(Date.now(),CT_GAS.budgetMs(PropertiesService.getScriptProperties().getProperty('CT_GAS_BUDGET_MS'))),result=parsed.operation==='evidence-ingest'?CT_GAS_FEDERATION.ingest(parsed,clock):CT_GAS_FEDERATION.consume(auth,clock);return ContentService.createTextOutput(JSON.stringify(result)).setMimeType(ContentService.MimeType.JSON);}catch(error){return ContentService.createTextOutput(JSON.stringify({status:'rejected',reason:federationRejectionReason(error)})).setMimeType(ContentService.MimeType.JSON);}}
function dispatchPendingFederationAdvisories(clock){var rows=CT_GAS_FEDERATION.rpc('pending',{p_limit:3},clock),out=[];(rows||[]).forEach(function(row){try{row.advisory=JSON.parse(row.advisoryText);out.push(CT_GAS_FEDERATION.consume(row,clock));}catch(_){out.push({status:'deferred',nonce:row.advisory&&row.advisory.nonce});}});return out;}
function inspectFederationIdentity(){var token=ScriptApp.getIdentityToken();if(!token)throw new Error('identity token unavailable; authorize the OpenID scopes first');var payload=JSON.parse(Utilities.newBlob(Utilities.base64DecodeWebSafe(token.split('.')[1])).getDataAsString());throw new Error('FEDERATION_IDENTITY '+JSON.stringify({aud:payload.aud,sub:payload.sub}));}
