var CT_GAS_AGENT = (function () {
  var failures=['rate_limited','quota_exhausted','insufficient_balance','model_unavailable','provider_unavailable','context_exceeded','malformed_or_invalid_request','transient_provider_error','model/output_failure','unknown'];
  function key() { var value=PropertiesService.getScriptProperties().getProperty('OPENROUTER_API_KEY'); if (!value) throw new Error('OPENROUTER_API_KEY is required'); return value; }
  function verifyFreePrice(model,secret) { var r=UrlFetchApp.fetch('https://openrouter.ai/api/v1/models',{method:'get',headers:{Authorization:'Bearer '+secret},muteHttpExceptions:true}), parsed; if (r.getResponseCode()<200 || r.getResponseCode()>=300) throw new Error('free-model-catalog-unavailable'); try { parsed=JSON.parse(CT_GAS.bound(r.getContentText(),1000000)); } catch (_) { throw new Error('free-model-catalog-invalid'); } var item=(parsed.data||[]).filter(function (x) { return String(x.id)===String(model); })[0], p=item&&item.pricing||{}, a=item&&item.architecture||{}; if (!item || String(p.prompt)!=='0' || String(p.completion)!=='0' || (a.input_modalities && a.input_modalities.indexOf('text')<0) || (a.output_modalities && a.output_modalities.indexOf('text')<0)) throw new Error('free-model-price-not-verified'); return item; }
  function safeText(value,secret) { return CT_GAS.redact(CT_GAS.bound(value,8000),[secret]); }
  function header(response,name) { var all=response&&response.getAllHeaders?response.getAllHeaders():{}, found=null; Object.keys(all||{}).some(function (k) { if (String(k).toLowerCase()===name) { found=all[k]; return true; } return false; }); return found==null?null:CT_GAS.bound(Array.isArray(found)?found.join(','):found,160); }
  function signal(parsed) { var e=parsed&&parsed.error||{}, m=e.metadata||{}; return [e.code,e.type,e.message,m.code,m.type,m.reason,m.provider_name].filter(function (x) { return typeof x==='string'||typeof x==='number'; }).join(' ').toLowerCase(); }
  function classify(code,parsed,errorClass) { var s=signal(parsed); if (errorClass==='urlfetch_error') return 'transient_provider_error'; if (code===429) { if (/balance|credit|fund/.test(s)) return 'insufficient_balance'; if (/quota|free.?tier|free.?model|daily|monthly|exhaust|limit.?reached/.test(s)) return 'quota_exhausted'; return 'rate_limited'; } if (code===402) return 'insufficient_balance'; if (code===404 || /model.+(unavailable|not found|disabled)/.test(s)) return 'model_unavailable'; if (/context|token.+(limit|maximum)|too many tokens/.test(s)) return 'context_exceeded'; if (code===400||code===413||code===422) return 'malformed_or_invalid_request'; if (code===408||code===409||code===425||code===504) return 'transient_provider_error'; if (code>=500) return 'provider_unavailable'; return 'unknown'; }
  function retryable(category) { return category==='rate_limited'||category==='provider_unavailable'||category==='transient_provider_error'||category==='model/output_failure'; }
  function provider(model) { return String(model||'').indexOf('openrouter/')===0?'openrouter':null; }
  function record(request,base) { var x=Object.assign({operation:'inference',execution_id:request.execution_id,physical_execution_id:request.physical_execution_id,work_order_id:request.work_order_id,wake_id:request.wake_id,continuation_id:request.continuation_id,requested_provider:request.provider||provider(request.model)||'openrouter',requested_model:request.model,canonical_provider:'openrouter',canonical_model:CT_GAS.canonicalModel(request.model),role:request.role||'executor',task_purpose:request.task_purpose||'bounded-model-turn',retry_count:Number(request.attempt||0),fallback_path:request.fallback_path||CT_GAS.canonicalModel(request.model),model_invocation_count:1},base); try { CT_GAS_STATE.telemetry(x); } catch (_) {} return x; }
  function failure(request,model,category,detail) { var n=Number(request.attempt||0)+1, canRetry=retryable(category)&&n<=5&&Date.now()<=Number(request.deadline||Date.now()+3600000), impossible=category==='quota_exhausted'||category==='insufficient_balance'||category==='model_unavailable'||category==='context_exceeded'||category==='malformed_or_invalid_request'; record(request,Object.assign({actual_model:null,failure_category:category,retry_count:n,retryable:canRetry,impossible_until_state_change:impossible},detail)); try { CT_GAS_STATE.event('model_deferred',{execution_id:request.execution_id,physical_execution_id:request.physical_execution_id,work_order_id:request.work_order_id,wake_id:request.wake_id,continuation_id:request.continuation_id,operation:'model',reason:category,attempt:n,model:model}); } catch (_) {} return {status:canRetry?'deferred':'blocked',model:model,reason:category,failure_category:category,attempt:n,retryable:canRetry,impossible_until_state_change:impossible,work_order_id:request.work_order_id,execution_id:request.execution_id,continuation_id:request.continuation_id}; }
  function execute(request) {
    request=request||{}; var requestedModel=request.model, model=CT_GAS.canonicalModel(requestedModel); CT_GAS.freeModel(model);
    var messages=CT_GAS.messages(request.messages), maxTokens=Math.min(Math.max(Number(request.maxTokens||512),1),1024), started=Date.now(), startedAt=new Date(started).toISOString(), secret=key(), response, catalog=null;
    if (Number(request.maxTurns||1)!==1) throw new Error('GAS executor permits one model turn per wake');
    messages=messages.map(function (m) { return {role:m.role,content:CT_GAS.redact(m.content,[secret])}; });
    try { var admitted=CT_GAS.runGuard(request.clock,'model-request',request.requiredMs||CT_GAS.OPERATION_BUDGETS.model,function () { if (request.verify_price) catalog=verifyFreePrice(model,secret); return UrlFetchApp.fetch('https://openrouter.ai/api/v1/chat/completions',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+secret},payload:JSON.stringify({model:model,messages:messages,max_tokens:maxTokens}),muteHttpExceptions:true}); }); if (admitted.status==='preempted') return admitted; response=admitted; if (!request.clock.canStart(0)) return {status:'preempted',operation:'model-request',reason:'post-operation-unsafe'}; }
    catch (_) { return failure(request,model,'transient_provider_error',{request_started_at:startedAt,response_received_at:new Date().toISOString(),latency_ms:Date.now()-started,error_class:'urlfetch_error',zero_price_verified:Boolean(catalog)}); }
    var received=new Date().toISOString(), code=response.getResponseCode(), parsed=null, parseFailed=false;
    try { parsed=JSON.parse(CT_GAS.bound(response.getContentText(),12000)); } catch (_) { parseFailed=true; }
    var err=parsed&&parsed.error||{}, metadata=err.metadata||{}, usage=parsed&&parsed.usage||{}, remaining=header(response,'x-ratelimit-remaining'), reset=header(response,'x-ratelimit-reset'), retryAfter=header(response,'retry-after');
    var common={request_started_at:startedAt,response_received_at:received,latency_ms:Date.now()-started,http_status:code,error_class:code>=200&&code<300?null:'http_'+code,actual_provider:metadata.provider_name||parsed&&parsed.provider||null,actual_model:parsed&&(parsed.model||parsed.id)||null,zero_price_verified:Boolean(catalog),context_limit:catalog&&catalog.context_length||null,prompt_tokens:usage.prompt_tokens,completion_tokens:usage.completion_tokens,total_tokens:usage.total_tokens,cost:usage.cost,cost_currency:usage.cost===undefined?null:'USD',quota_remaining:remaining,quota_reset_at:reset,quota_retry_after_ms:retryAfter&&/^\d+(?:\.\d+)?$/.test(retryAfter)?Math.round(Number(retryAfter)*1000):null,quota_authoritative:Boolean(remaining!==null||reset!==null||retryAfter!==null)};
    if (code<200||code>=300) { var category=classify(code,parsed,common.error_class); return failure(request,model,category,common); }
    var output=parsed&&parsed.choices&&parsed.choices[0]&&parsed.choices[0].message&&parsed.choices[0].message.content;
    if (parseFailed||typeof output!=='string'||!output.length) return failure(request,model,'model/output_failure',Object.assign(common,{error_class:parseFailed?'invalid_json':'missing_output'}));
    record(request,Object.assign(common,{failure_category:null,retryable:false,impossible_until_state_change:false,actual_model:common.actual_model||model,turns:1,elapsed_ms:Date.now()-started}));
    return {status:'complete',model:common.actual_model||model,requested_model:requestedModel,turns:1,elapsed_ms:Date.now()-started,output:safeText(output,secret)};
  }
  return {execute:execute,failure_categories:failures};
}());
function executeAgent(request) { return CT_GAS_AGENT.execute(request); }
