/* Narrow, separately authenticated self-deployment capability. */
var CT_GAS_DEPLOY = (function () {
  var API = 'https://script.googleapis.com/v1';
  var MAX_FILES = 64;
  var MAX_FILE_BYTES = 262144;
  var MAX_BUNDLE_BYTES = 2097152;
  var MAX_RESPONSE_BYTES = 4194304;
  var MAX_NONCES = 256;
  var NONCE_TTL_MS = 10 * 60 * 1000;
  var CLOCK_SKEW_SEC = 300;
  var NONCE_PROPERTY = 'CT_GAS_DEPLOY_NONCES';
  var REQUEST_PREFIX = 'CT_GAS_DEPLOY_REQUEST_';
  function props() { return PropertiesService.getScriptProperties(); }
  function equal(a,b){a=String(a||'');b=String(b||'');var n=Math.max(a.length,b.length),diff=a.length^b.length;for(var i=0;i<n;i++)diff|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return diff===0;}
  function hex(bytes){return bytes.map(function(b){return ('0'+(b<0?b+256:b).toString(16)).slice(-2);}).join('');}
  function digest(value){return hex(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value,Utilities.Charset.UTF_8));}
  function hmac(value,secret){return hex(Utilities.computeHmacSha256Signature(value,secret,Utilities.Charset.UTF_8));}
  function bytes(value){return Utilities.newBlob(String(value),'text/plain').getBytes().length;}
  function fail(message){throw new Error('deploy-'+message);}
  function json(value){return JSON.stringify(value);}
  function path(id){return encodeURIComponent(String(id));}
  function api(method,url,body){var options={method:method,headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken()},muteHttpExceptions:true};if(body!==undefined){options.contentType='application/json';options.payload=json(body);}var response=UrlFetchApp.fetch(url,options),text=response.getContentText();if(bytes(text)>MAX_RESPONSE_BYTES)fail('google-response-too-large');var code=response.getResponseCode();if(code<200||code>=300){var detail={};try{detail=JSON.parse(text);}catch(_){}throw new Error('deploy-google-api-'+code+' '+String(detail.error&&detail.error.message||'').slice(0,300));}try{return JSON.parse(text);}catch(_){fail('google-response-invalid-json');}}
  function ownScriptId(){return String(ScriptApp.getScriptId());}
  function configuredDeploymentId(){return String(props().getProperty('CT_GAS_DEPLOYMENT_ID')||'');}
  function deployment(scriptId,deploymentId){return api('get',API+'/projects/'+path(scriptId)+'/deployments/'+path(deploymentId));}
  function content(scriptId,versionNumber){var url=API+'/projects/'+path(scriptId)+'/content';if(versionNumber!==undefined&&versionNumber!==null)url+='?versionNumber='+encodeURIComponent(String(versionNumber));return api('get',url);}
  function version(scriptId,versionNumber){return api('get',API+'/projects/'+path(scriptId)+'/versions/'+path(versionNumber));}
  function versions(scriptId){return api('get',API+'/projects/'+path(scriptId)+'/versions?pageSize=100');}
  function normalizeFiles(files){if(!Array.isArray(files)||!files.length||files.length>MAX_FILES)fail('invalid-file-count');var seen={},manifest=0,out=[];files.forEach(function(file){if(!file||typeof file!=='object'||typeof file.name!=='string'||typeof file.source!=='string'||typeof file.type!=='string')fail('invalid-file');if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(file.name)||file.name.indexOf('..')>=0||file.name.indexOf('/')>=0||file.name.indexOf('\\')>=0)fail('invalid-file-name');if(seen[file.name])fail('duplicate-file');seen[file.name]=true;if(['SERVER_JS','HTML','JSON'].indexOf(file.type)<0)fail('invalid-file-type');if(file.name==='appsscript.json'){if(file.type!=='JSON')fail('invalid-manifest-type');manifest++;}else if(file.type==='JSON')fail('unexpected-json-file');if(bytes(file.source)>MAX_FILE_BYTES)fail('file-too-large');out.push({name:file.name,type:file.type,source:file.source});});if(manifest!==1)fail('manifest-required');out.sort(function(a,b){return a.name<b.name?-1:a.name>b.name?1:0;});if(bytes(json(out))>MAX_BUNDLE_BYTES)fail('bundle-too-large');return out;}
  function bundleHash(files){return digest(json(normalizeFiles(files)));}
  function contentHash(project){return bundleHash(project.files||[]);}
  function marker(description){var text=String(description||''),out={};text.split(/\s+/).forEach(function(part){var i=part.indexOf('=');if(i>0)out[part.slice(0,i)]=part.slice(i+1);});return text.indexOf('ct-runtime-deploy')>=0?out:null;}
  function markerDescription(request){return 'ct-runtime-deploy request_id='+request.deployment_request_id+' commit='+request.commit_sha+' bundle='+request.bundle_hash;}
  function verifyMarker(v,request){var m=marker(v&&v.description);return !!m&&m.request_id===request.deployment_request_id&&m.commit===request.commit_sha&&m.bundle===request.bundle_hash;}
  function parseVersions(result){return Array.isArray(result&&result.versions)?result.versions:[];}
  function recoverVersion(scriptId,request){var matches=parseVersions(versions(scriptId)).filter(function(v){return verifyMarker(v,request);});if(!matches.length)return null;matches.sort(function(a,b){return Number(b.versionNumber)-Number(a.versionNumber);});return matches[0];}
  function nonceHash(nonce){return digest(String(nonce));}
  function reserveNonce(nonce){var lock=LockService.getScriptLock();lock.waitLock(10000);try{var now=Date.now(),hash=nonceHash(nonce),rows=[];try{rows=JSON.parse(props().getProperty(NONCE_PROPERTY)||'[]');}catch(_){rows=[];}rows=rows.filter(function(row){return row&&Number(row.expiresAt)>now;});for(var i=0;i<rows.length;i++)if(rows[i].hash===hash)fail('nonce-replay');rows.push({hash:hash,expiresAt:now+NONCE_TTL_MS});if(rows.length>MAX_NONCES)rows=rows.slice(rows.length-MAX_NONCES);props().setProperty(NONCE_PROPERTY,json(rows));}finally{lock.releaseLock();}}
  function requestFence(request){var key=REQUEST_PREFIX+digest(request.deployment_request_id).slice(0,48),lock=LockService.getScriptLock();lock.waitLock(10000);try{var prior=props().getProperty(key),identity=request.commit_sha+':'+request.bundle_hash;if(prior&&prior!==identity)fail('request-conflict');props().setProperty(key,identity);}finally{lock.releaseLock();}}
  function authenticate(raw,query){var timestamp=String(query.timestamp||''),nonce=String(query.nonce||''),signature=String(query.signature||''),secret=props().getProperty('CT_GAS_DEPLOY_HMAC_SECRET');if(!secret||!timestamp||!nonce||!signature)fail('authentication-missing');var seconds=Number(timestamp),now=Math.floor(Date.now()/1000);if(!/^\d+$/.test(timestamp)||!Number.isSafeInteger(seconds)||Math.abs(now-seconds)>CLOCK_SKEW_SEC)fail('authentication-skew');var request;try{request=JSON.parse(raw);}catch(_){fail('invalid-json');}if(request.operation!=='self-deploy'&&request.operation!=='self-deploy-plan'&&request.operation!=='self-deploy-qualify')fail('operation-not-allowed');var bodyHash=digest(raw),signed=[request.operation,timestamp,nonce,request.deployment_request_id||'',request.script_id||'',request.deployment_id||'',request.commit_sha||'',request.bundle_hash||'',bodyHash].join('\n');if(!equal(signature,hmac(signed,secret)))fail('authentication-signature');reserveNonce(nonce);return request;}
  function validateRequest(request){if(!/^[0-9a-f]{40}$/.test(String(request.commit_sha||'')))fail('invalid-commit');if(!/^[0-9a-f]{64}$/.test(String(request.bundle_hash||'')))fail('invalid-bundle-hash');if(!/^[A-Za-z0-9][A-Za-z0-9._-]{7,127}$/.test(String(request.deployment_request_id||'')))fail('invalid-request-id');if(!/^[A-Za-z0-9][A-Za-z0-9._-]{7,127}$/.test(String(request.deployment_id||'')))fail('invalid-deployment-id');if(!/^[A-Za-z0-9_-]{20,100}$/.test(String(request.script_id||'')))fail('invalid-script-id');}
  function liveState(request){if(ownScriptId()!==request.script_id)fail('script-id-mismatch');var configured=configuredDeploymentId();if(!configured||configured!==request.deployment_id)fail('deployment-id-mismatch');var dep=deployment(request.script_id,request.deployment_id),versionNumber=String(dep.versionNumber||'');if(!versionNumber)fail('deployment-version-missing');var liveContent=content(request.script_id,versionNumber);return {deployment:dep,versionNumber:versionNumber,bundleHash:contentHash(liveContent),content:liveContent};}
  function expectedFence(request,live){if(String(request.expected_live_version||'')!==String(live.versionNumber)||String(request.expected_live_bundle_hash||'')!==String(live.bundleHash))fail('live-state-conflict');}
  function head(request){var value=content(request.script_id);return {content:value,bundleHash:contentHash(value)};}
  function updateHead(request,files){return api('put',API+'/projects/'+path(request.script_id)+'/content',{files:files});}
  function createVersion(request){return api('post',API+'/projects/'+path(request.script_id)+'/versions',{description:markerDescription(request)});}
  function updateDeployment(request,versionNumber){return api('patch',API+'/projects/'+path(request.script_id)+'/deployments/'+path(request.deployment_id),{deploymentConfig:{versionNumber:String(versionNumber)}});}
  function qualify(request){if(ownScriptId()!==request.script_id)fail('script-id-mismatch');var value=content(request.script_id);return {status:'qualified',scriptId:request.script_id,headBundleHash:contentHash(value),fileCount:(value.files||[]).length};}
  function plan(request){var live=liveState(request),h=head(request);return {status:'planned',scriptId:request.script_id,deploymentId:request.deployment_id,liveVersion:live.versionNumber,liveBundleHash:live.bundleHash,headBundleHash:h.bundleHash};}
  function deploy(request,files){validateRequest(request);var normalized=normalizeFiles(files),actualHash=bundleHash(normalized);if(actualHash!==request.bundle_hash)fail('bundle-hash-mismatch');requestFence(request);var live=liveState(request);if(verifyMarker(version(request.script_id,live.versionNumber),request)){var deployed=content(request.script_id,live.versionNumber);if(contentHash(deployed)!==request.bundle_hash)fail('marker-content-mismatch');return {status:'verified',requestId:request.deployment_request_id,versionNumber:live.versionNumber,deploymentId:request.deployment_id,bundleHash:request.bundle_hash};}expectedFence(request,live);var h=head(request);if(h.bundleHash!==request.bundle_hash)updateHead(request,normalized);var recovered=recoverVersion(request.script_id,request),v=recovered||createVersion(request),versionNumber=String(v.versionNumber||'');if(!versionNumber)fail('version-number-missing');if(String(live.versionNumber)!==versionNumber)updateDeployment(request,versionNumber);var finalDep=deployment(request.script_id,request.deployment_id),finalVersion=String(finalDep.versionNumber||'');if(finalVersion!==versionNumber)fail('readback-deployment-mismatch');var finalContent=content(request.script_id,finalVersion),finalHash=contentHash(finalContent);if(finalHash!==request.bundle_hash)fail('readback-bundle-mismatch');var finalVersionInfo=version(request.script_id,finalVersion);if(!verifyMarker(finalVersionInfo,request))fail('readback-marker-mismatch');var finalHead=head(request);if(finalHead.bundleHash!==request.bundle_hash)fail('readback-head-mismatch');return {status:'verified',requestId:request.deployment_request_id,versionNumber:finalVersion,deploymentId:request.deployment_id,bundleHash:finalHash,headBundleHash:finalHead.bundleHash,fileCount:(finalContent.files||[]).length};}
  return {authenticate:authenticate,qualify:qualify,plan:plan,deploy:deploy,bounds:{maxFiles:MAX_FILES,maxFileBytes:MAX_FILE_BYTES,maxBundleBytes:MAX_BUNDLE_BYTES}};
}());
function selfDeployRejectionReason(error){var message=String(error&&error.message||'');return message.indexOf('deploy-')===0?message:'deploy-internal-error';}
