var CT_GAS_AGENT = (function () {
   function key() { var value=PropertiesService.getScriptProperties().getProperty('OPENROUTER_API_KEY'); if (!value) throw new Error('OPENROUTER_API_KEY is required'); return value; }
   function verifyFreePrice(model,secret) { var r=UrlFetchApp.fetch('https://openrouter.ai/api/v1/models',{method:'get',headers:{Authorization:'Bearer '+secret},muteHttpExceptions:true}), parsed; if (r.getResponseCode()<200 || r.getResponseCode()>=300) throw new Error('free-model-catalog-unavailable'); try { parsed=JSON.parse(CT_GAS.bound(r.getContentText(),1000000)); } catch (_) { throw new Error('free-model-catalog-invalid'); } var item=(parsed.data||[]).filter(function (x) { return String(x.id)===String(model); })[0], p=item&&item.pricing||{}, a=item&&item.architecture||{}; if (!item || String(p.prompt)!=='0' || String(p.completion)!=='0' || (a.input_modalities && a.input_modalities.indexOf('text')<0) || (a.output_modalities && a.output_modalities.indexOf('text')<0)) throw new Error('free-model-price-not-verified'); return item;
   }
  function safeText(value) { return CT_GAS.redact(CT_GAS.bound(value,8000),[key()]); }
   function defer(request, model, reason, attempt) { var n=Number(attempt || 0)+1; if (n > 5 || Date.now() > Number(request.deadline || Date.now()+3600000)) return {status:'failed',model:model,reason:'retry-deadline',attempt:n,work_order_id:request.work_order_id,execution_id:request.execution_id,continuation_id:request.continuation_id}; try { CT_GAS_STATE.event('model_deferred',{execution_id:request.execution_id,physical_execution_id:request.physical_execution_id,work_order_id:request.work_order_id,wake_id:request.wake_id,continuation_id:request.continuation_id,operation:'model',reason:reason,attempt:n,model:model}); } catch (_) {} return {status:'deferred',model:model,attempt:n,work_order_id:request.work_order_id,execution_id:request.execution_id,continuation_id:request.continuation_id}; }
   function execute(request) { request=request || {}; var requestedModel=request.model, model=CT_GAS.canonicalModel(requestedModel); CT_GAS.freeModel(model); var messages=CT_GAS.messages(request.messages), maxTokens=Math.min(Math.max(Number(request.maxTokens || 512),1),1024), started=Date.now(), secret=key(), response; if (Number(request.maxTurns || 1) !== 1) throw new Error('GAS executor permits one model turn per wake'); messages=messages.map(function (m) { return {role:m.role,content:CT_GAS.redact(m.content,[secret])}; }); try { var admitted=CT_GAS.runGuard(request.clock,'model-request',request.requiredMs || CT_GAS.OPERATION_BUDGETS.model,function () { if (request.verify_price) verifyFreePrice(model,secret); return UrlFetchApp.fetch('https://openrouter.ai/api/v1/chat/completions',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+secret},payload:JSON.stringify({model:model,messages:messages,max_tokens:maxTokens}),muteHttpExceptions:true}); }); if (admitted.status==='preempted') return admitted; response=admitted; if (!request.clock.canStart(0)) return {status:'preempted',operation:'model-request',reason:'post-operation-unsafe'}; } catch (_) { return defer(request,model,'network',request.attempt); } var code=response.getResponseCode(); if (code===429 || code>=500) return defer(request,model,code===429?'rate-limit':'provider',request.attempt); if (code<200 || code>=300) throw new Error('OpenRouter request failed: '+code); var parsed; try { parsed=JSON.parse(CT_GAS.bound(response.getContentText(),12000)); } catch (_) { throw new Error('invalid model response'); } var output=parsed.choices && parsed.choices[0] && parsed.choices[0].message && parsed.choices[0].message.content; return {status:'complete',model:model,requested_model:requestedModel,turns:1,elapsed_ms:Date.now()-started,output:safeText(output)}; }
  return {execute:execute};
}());
function executeAgent(request) { return CT_GAS_AGENT.execute(request); }
