var CT_GAS_TRIGGER = (function () {
  var safety = 'gasSafetyWake', marker = 'CT_GAS_SAFETY_TRIGGER';
  function registry() { return ScriptApp.getProjectTriggers().map(function (t) { return { handler:t.getHandlerFunction(), source:String(t.getTriggerSource()), id:t.getUniqueId ? t.getUniqueId() : null }; }); }
  function ensure() { var l=LockService.getScriptLock(); l.waitLock(20000); try { var props=PropertiesService.getScriptProperties(), found=registry().filter(function (x) { return x.handler === safety; }); if (found.length) { props.setProperty(marker,'present'); return found; } ScriptApp.newTrigger(safety).timeBased().everyMinutes(15).create(); props.setProperty(marker,'present'); return registry().filter(function (x) { return x.handler === safety; }); } finally { l.releaseLock(); } }
  function schedule(wake,clock) { var normalized=CT_GAS.wake(wake), own=clock||CT_GAS.clock(Date.now(),PropertiesService.getScriptProperties().getProperty('CT_GAS_BUDGET_MS')), result=CT_GAS.runGuard(own,'trigger-schedule',CT_GAS.OPERATION_BUDGETS.trigger,function () { var row=CT_GAS_STATE.schedule(normalized); if (!own.canStart(CT_GAS.OPERATION_BUDGETS.trigger)) return {status:'preempted',reason:'post-schedule-checkpoint'}; var ensured=CT_GAS.runGuard(own,'trigger-ensure',CT_GAS.OPERATION_BUDGETS.trigger,ensure); if (ensured.status==='preempted') return ensured; PropertiesService.getScriptProperties().setProperty('CT_GAS_WAKE_' + row.idempotency_key,'recorded'); return row; }); if (result.status==='preempted') throw new Error('insufficient budget for trigger scheduling'); return result; }
  function due(now,clock) { return CT_GAS.runGuard(clock||CT_GAS.clock(Date.now(),CT_GAS.BUDGET_MS),'state-read-wakes',CT_GAS.OPERATION_BUDGETS.stateRead,function () { var rows=CT_GAS_STATE.list('wakes'); return rows.filter(function (x,i,a) { return !a.some(function (y) { return y.id===x.id && Number(y.revision||0)>Number(x.revision||0); }); }).filter(function (x) { return (x.lifecycle === 'pending' || (x.lifecycle === 'claimed' && new Date(x.lease_until || 0).getTime() <= now)) && x.payload && new Date(x.payload.time).getTime() <= now; }); }); }
  return { registry:registry, ensure:ensure, schedule:schedule, due:due };
}());
 function gasSafetyWake() { var now=Date.now(), budget=CT_GAS.budgetMs(PropertiesService.getScriptProperties().getProperty('CT_GAS_BUDGET_MS')), clock=CT_GAS.clock(now,budget), out=[]; var ensured=CT_GAS.runGuard(clock,'trigger-ensure',CT_GAS.OPERATION_BUDGETS.trigger,CT_GAS_TRIGGER.ensure); if (ensured.status==='preempted') return [{status:'interrupted',reason:'insufficient-budget-for-trigger'}];
   /* A recurring safety trigger repairs the only non-atomic boundary: persisted work without a wake. */
    try { if (PropertiesService.getScriptProperties().getProperty('CT_GAS_FEDERATION_DATA_API_URL') && clock.canStart(CT_GAS.OPERATION_BUDGETS.trigger)) dispatchPendingFederationAdvisories(clock); } catch (_) {}
    try { var orders=CT_GAS_STATE.list('work_orders'); for (var oi=0;oi<orders.length;oi++) { var order=orders[oi], cp=CT_GAS_STATE.latestContinuation(order.id); if ((order.lifecycle==='checkpointed'||order.lifecycle==='deferred') && cp && clock.canStart(CT_GAS.OPERATION_BUDGETS.trigger)) { var wakes=CT_GAS_STATE.list('wakes').filter(function (w) { return w.payload && w.payload.work_order_id===order.id && w.payload.continuation_id===cp.continuation_id && w.lifecycle!=='completed'; }); if (!wakes.length) { try { CT_GAS_TRIGGER.schedule({time:new Date(now+1000).toISOString(),reason:order.lifecycle==='deferred'?'model-deferred':'recovery',work_order_id:order.id,execution_id:cp.execution_id,continuation_id:cp.continuation_id,launch:cp.launch_context,resume:cp.resume_context},clock); } catch (_) {} } } } } catch (_) {}
    var rows=CT_GAS_TRIGGER.due(now,clock); if (rows.status==='preempted') return [{status:'interrupted',reason:'insufficient-budget-for-wake-read'}]; rows=rows.slice(0,3); for (var i=0;i<rows.length;i++) { var row=rows[i], p=row.payload||{}, identity=p.work_order_id&&p.execution_id&&p.continuation_id, fence=CT_GAS.id('fence',{id:row.id,sequence:i,at:now}); try { if (!identity) { var invalid=CT_GAS_STATE.invalid(row.id,'missing-wake-identity'); var event=CT_GAS_STATE.event('invalid_wake',{wake_id:row.id,operation:'wake-dispatch',reason:'missing-wake-identity',general_compute_requested:false}); out.push({status:'invalid',wake_id:row.id,reason:'invalid-wake-identity',event_id:event.id}); continue; } var claimed=CT_GAS.runGuard(clock,'wake-claim',CT_GAS.OPERATION_BUDGETS.stateWrite,function () { return CT_GAS_STATE.claim(row.id,'gas-safety',fence,new Date(now+budget).toISOString()); }); if (claimed.status==='preempted') break; var result=runWake({work_order_id:p.work_order_id,execution_id:p.execution_id,continuation_id:p.continuation_id,launch:p.launch,resume:p.resume,wake_id:row.id}); if (result.status==='checkpointed'||result.status==='complete') { try { var complete=CT_GAS.runGuard(clock,'wake-complete',CT_GAS.OPERATION_BUDGETS.stateWrite,function () { return CT_GAS_STATE.complete(row.id,{status:'dispatched'},'gas-safety',fence); }); if (complete.status==='preempted') result={status:'interrupted',reason:'wake-completion-uncommitted',work_order_id:p.work_order_id}; } catch (_) { result={status:'interrupted',reason:'wake-completion-failed',work_order_id:p.work_order_id}; } } out.push(result); } catch (e) { out.push({status:'deferred',wake_id:row.id,work_order_id:p.work_order_id,execution_id:p.execution_id,continuation_id:p.continuation_id,error:String(e.message||e)}); } } return out; }
function requestNextWake(wake) { return CT_GAS_TRIGGER.schedule(wake); }
function triggerRegistry() { return CT_GAS_TRIGGER.registry(); }
