/* Serialized single-writer Sheets adapter. Public mutations lock once; primitives never lock. */
var CT_GAS_STATE = (function () {
  var headers = ['id','kind','lifecycle','execution_id','parent_id','worker_id','idempotency_key','payload_json','created_at','updated_at','schema_version','revision','supersedes','owner','fence','lease_until'];
  var kinds = { executions:1, work_orders:1, wakes:1, continuations:1, observer_ledger:1, memory:1, lessons:1, identity_signals:1, foundry_signals:1, model_telemetry:1, evidence:1, chronicle:1, schema:1 };
  function book() { var id = PropertiesService.getScriptProperties().getProperty('CT_GAS_SPREADSHEET_ID'); if (!id) throw new Error('CT_GAS_SPREADSHEET_ID is required'); return SpreadsheetApp.openById(id); }
  function lock(fn) { var l = LockService.getScriptLock(); l.waitLock(20000); try { return fn(); } finally { l.releaseLock(); } }
  function sheet(name) { if (!kinds[name]) throw new Error('unsupported GAS sheet/kind'); var b = book(); var s = b.getSheetByName(name) || b.insertSheet(name); if (s.getLastRow() === 0) s.appendRow(headers); return s; }
  function read(name) { var values = sheet(name).getDataRange().getValues(); return values.slice(1).filter(function (r) { return r[0]; }).map(function (r) { var x = {}; headers.forEach(function (h, i) { x[h] = r[i]; }); try { x.payload = JSON.parse(x.payload_json || '{}'); } catch (_) { x.payload = {}; } return x; }); }
  function appendUnlocked(name, row) { var now = new Date().toISOString(), x = Object.assign({ created_at:now, updated_at:now, schema_version:'gas-v2', payload:{}, revision:1 }, row), json = JSON.stringify(x.payload || {}); if (json.length > CT_GAS.MAX_PAYLOAD) throw new Error('payload exceeds bound'); sheet(name).appendRow(headers.map(function (h) { return h === 'payload_json' ? json : (x[h] == null ? '' : x[h]); })); return x; }
  function latest(name, id) { var rows = read(name).filter(function (x) { return x.id === id; }); rows.sort(function (a,b) { return Number(a.revision || 0) - Number(b.revision || 0); }); return rows.filter(function (x, i) { return i === 0 || x.supersedes === id || x.supersedes === rows[i - 1].id; }).pop() || null; }
  function same(a,b) { return CT_GAS.json(a || {}) === CT_GAS.json(b || {}); }
  function createUnlocked(kind, data) { if (!kinds[kind]) throw new Error('unsupported GAS kind'); var id = data.id || CT_GAS.id(kind,data), idem = data.idempotency_key || CT_GAS.id('idem',data), old = latest(kind,id); if (old) { if (!same(old.payload,data.payload || data)) throw new Error('idempotency conflict'); return old; } var conflicts = read(kind).filter(function (x) { return x.idempotency_key === idem; }); if (conflicts.length) { if (!same(conflicts[conflicts.length - 1].payload,data.payload || data)) throw new Error('idempotency key conflict'); return conflicts[conflicts.length - 1]; } return appendUnlocked(kind,Object.assign({id:id,kind:kind,idempotency_key:idem},data)); }
   function mutateUnlocked(kind,id,patch) { var old=latest(kind,id); if (!old) throw new Error('record not found'); if (patch.lifecycle) CT_GAS.transition(old.lifecycle,patch.lifecycle); return appendUnlocked(kind,Object.assign({},old,patch,{id:id,kind:kind,revision:Number(old.revision || 0)+1,supersedes:id,payload:Object.assign({},old.payload || {},patch.payload || {})})); }
   function mutate(kind,id,patch) { return lock(function () { return mutateUnlocked(kind,id,patch); }); }
   function scheduleUnlocked(wake) { wake=CT_GAS.wake(wake); var key=CT_GAS.id('wake-key',{work_order_id:wake.work_order_id,execution_id:wake.execution_id,continuation_id:wake.continuation_id,reason:wake.reason}), found=read('wakes').filter(function (x) { return x.idempotency_key === key; }); if (found.length) return latest('wakes',found[0].id); wake.execution_id=wake.execution_id || CT_GAS.id('execution',wake); wake.work_order_id=wake.work_order_id || CT_GAS.id('work-order',wake); return appendUnlocked('wakes',{id:CT_GAS.id('wake',wake),kind:'wake',lifecycle:'pending',idempotency_key:key,payload:wake}); }
     function event(n,d) { return lock(function () { d=d || {}; var p=PropertiesService.getScriptProperties(), seq=Number(p.getProperty('CT_GAS_EVENT_SEQUENCE')||0)+1, secrets=['OPENROUTER_API_KEY','GITHUB_TOKEN'].map(function (name) { return p.getProperty(name); }).filter(Boolean), safe=JSON.parse(CT_GAS.redact(CT_GAS.bound(CT_GAS.json(d),CT_GAS.MAX_PAYLOAD),secrets)); p.setProperty('CT_GAS_EVENT_SEQUENCE',String(seq)); var x=Object.assign({},safe,{event_name:String(n).slice(0,80),event_sequence:seq,physical_event_id:CT_GAS.id('physical-event',{sequence:seq,name:n,data:safe})}); return appendUnlocked('observer_ledger',{id:x.physical_event_id,kind:n,execution_id:x.execution_id,payload:x}); }); }
   function latestContinuation(workOrderId) { return read('continuations').filter(function (x) { return x.payload && x.payload.work_order_id===workOrderId; }).sort(function (a,b) { var t=new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime(); return t || Number(b.revision||0)-Number(a.revision||0) || String(b.id).localeCompare(String(a.id)); }).map(function (x) { try { return CT_GAS.validateContinuation(x.payload); } catch (_) { return null; } }).filter(Boolean)[0] || null; }
     function telemetry(d) { return lock(function () { var allowed=['budget_ms','actual_duration_ms','voluntary_preemption','continuation_reason','resumed_from_execution','resumed_from_work_order','checkpoint_latency_ms','physical_execution_count','physical_execution_id','parent_physical_execution_id','model_invocation_count','checkpoint_count','reconstruction_source','requested_model','canonical_model','actual_model','fallback_from','fallback_to','zero_price_verified','work_lost_or_repeated','general_compute_requested','general_compute_reason','execution_id','work_order_id','wake_id','continuation_id','operation','wait_condition','defer_reason','capability_reason','model','turns','elapsed_ms','step','verified']; var x={}, secrets=['OPENROUTER_API_KEY','GITHUB_TOKEN'].map(function (n) { return PropertiesService.getScriptProperties().getProperty(n); }); allowed.forEach(function (k) { if (d && d[k] !== undefined && (typeof d[k]==='string'||typeof d[k]==='number'||typeof d[k]==='boolean'||d[k]===null)) x[k]=typeof d[k]==='string'?CT_GAS.redact(d[k],secrets):d[k]; }); x=Object.assign({budget_ms:CT_GAS.BUDGET_MS,actual_duration_ms:0,voluntary_preemption:false,general_compute_requested:false},x); if (x.general_compute_requested && CT_GAS.CAPABILITY_REASONS.indexOf(x.capability_reason)<0) throw new Error('exact capability reason is required'); if (x.general_compute_reason && x.general_compute_reason.indexOf('duration')>=0) throw new Error('duration cannot request general_compute'); var p=PropertiesService.getScriptProperties(), seq=Number(p.getProperty('CT_GAS_TELEMETRY_SEQUENCE')||0)+1; p.setProperty('CT_GAS_TELEMETRY_SEQUENCE',String(seq)); x.event_sequence=seq; x.physical_event_id=CT_GAS.id('telemetry-event',{sequence:seq,data:x}); return appendUnlocked('model_telemetry',{id:x.physical_event_id,kind:'model',execution_id:x.execution_id,payload:x}); }); }
     function executionStart(d) { d=d||{}; var id=CT_GAS.id('physical-execution',{work_order_id:d.work_order_id,parent_execution_id:d.parent_execution_id||'',wake_id:d.wake_id||'',created_at:new Date().toISOString(),nonce:String(Math.random())}); return lock(function () { return createUnlocked('executions',{id:id,kind:'execution',execution_id:id,parent_id:d.parent_execution_id||'',lifecycle:'running',payload:Object.assign({},d,{physical_execution_id:id,start_at:new Date().toISOString(),model_invocation_count:0,checkpoint_count:0,evidence_refs:[]})}); }); }
     function executionFinish(id,patch) { return lock(function () { var row=latest('executions',id); if (!row) throw new Error('physical execution not found'); return appendUnlocked('executions',Object.assign({},row,{id:id,kind:'execution',execution_id:id,revision:Number(row.revision||0)+1,supersedes:id,lifecycle:patch.lifecycle||'completed',payload:Object.assign({},row.payload||{},patch,{end_at:new Date().toISOString()})})); }); }
     function physicalExecutionCount(workOrderId) { var ids={}; read('executions').forEach(function (row) { if (row.payload && row.payload.work_order_id===workOrderId) ids[row.id]=true; }); return Object.keys(ids).length; }
     function observerObserved(executionId,workOrderId,continuationId,digest) { return read('observer_ledger').some(function (row) { return row.kind==='observer_observed' && row.payload && row.payload.execution_id===executionId && row.payload.work_order_id===workOrderId && row.payload.continuation_id===continuationId && row.payload.digest===digest; }); }
     return { headers:headers, initialize:function () { return lock(function () { CT_GAS.SHEETS.forEach(sheet); return CT_GAS.SHEETS; }); }, lock:lock, read:read, list:read, get:latest, latestContinuation:latestContinuation, physicalExecutionCount:physicalExecutionCount, observerObserved:observerObserved, executionStart:executionStart, executionFinish:executionFinish, append:function (n,r) { return lock(function () { return appendUnlocked(n,r); }); }, create:function (k,d) { return lock(function () { return createUnlocked(k,d); }); }, update:mutate, event:event, schedule:function (w) { return lock(function () { return scheduleUnlocked(w); }); }, claim:function (id,owner,fence,expires) { return lock(function () { var row=latest('wakes',id), expired=row && row.lifecycle==='claimed' && new Date(row.lease_until||0).getTime()<=Date.now(); if (!row || (row.lifecycle!=='pending' && !expired) || (row.lifecycle==='claimed' && !expired && row.owner!==owner)) throw new Error('wake claim rejected'); return mutateUnlocked('wakes',id,{lifecycle:'claimed',owner:owner,fence:fence,lease_until:expires}); }); }, complete:function (id,data,owner,fence) { return lock(function () { var row=latest('wakes',id); if (!row || row.lifecycle!=='claimed' || row.owner !== owner || String(row.fence) !== String(fence)) throw new Error('wake fence mismatch'); return mutateUnlocked('wakes',id,{lifecycle:'completed',payload:{result:data}}); }); }, invalid:function (id,data) { return lock(function () { return mutateUnlocked('wakes',id,{lifecycle:'invalid',payload:{invalid_reason:data}}); }); }, continuation:function (d) { var c=CT_GAS.continuation(d), id=c.continuation_id || CT_GAS.id('continuation',c); return lock(function () { return createUnlocked('continuations',{id:id,kind:'continuation',execution_id:c.resumed_from,payload:c}); }); }, telemetry:telemetry, evidenceRef:function (d) { return lock(function () { return createUnlocked('evidence',{id:CT_GAS.id('evidence-ref',d),kind:'reference',execution_id:d.execution_id,payload:d}); }) } };
}());
function initializeGasSchema() { return CT_GAS_STATE.initialize(); }
