var CT_GAS_OBSERVER = (function () {
  function consume(d) {
    d=d||{}; if (!d.clock) throw new Error('active clock is required for observer');
    var inbox=CT_GAS_EVIDENCE.folders()[1], files=inbox.getFiles(), count=0, results=[];
    while (files.hasNext() && count<Number(d.limit||3) && d.clock.canStart(CT_GAS.OPERATION_BUDGETS.observer)) {
      var file=files.next(), text=CT_GAS.bound(file.getBlob().getDataAsString(),CT_GAS.MAX_EVIDENCE_BYTES), value;
      try { value=JSON.parse(text); validate(value,text); } catch (error) { quarantine(file,error); results.push({status:'quarantined',file_id:file.getId()}); count++; continue; }
      var identity=value.evidenceId+'|'+value.contentHash, id=CT_GAS.id('observer-processing',identity), prior=CT_GAS_STATE.get('observer_processing',id);
       if (prior && prior.payload && (prior.payload.state==='observed' || prior.payload.state==='semantic-evidence-insufficient')) { file.moveTo(CT_GAS_EVIDENCE.folders()[2]); results.push({status:'duplicate',evidenceId:value.evidenceId}); count++; continue; }
      if (!prior) CT_GAS_STATE.create('observer_processing',{id:id,kind:'processing',payload:{identity:identity,evidence_id:value.evidenceId,physical_execution_id:value.physicalExecutionId,state:'claimed'}});
        try { var eligibility=semanticEligibility(value); if (!eligibility.eligible) { CT_GAS_STATE.update('observer_processing',id,{payload:{identity:identity,evidence_id:value.evidenceId,physical_execution_id:value.physicalExecutionId,state:'semantic-evidence-insufficient',reason:eligibility.reason} }); file.moveTo(CT_GAS_EVIDENCE.folders()[2]); results.push({status:'semantic-evidence-insufficient',evidenceId:value.evidenceId}); count++; continue; } if (typeof d.analyzer!=='function') throw new Error('semantic inference provider unavailable'); var semantic=d.analyzer(value); var observation=appendObservation(value,semantic); CT_GAS_STATE.update('observer_processing',id,{payload:{identity:identity,evidence_id:value.evidenceId,physical_execution_id:value.physicalExecutionId,state:'observed',observation_id:observation.observation_id,reason:null}}); file.moveTo(CT_GAS_EVIDENCE.folders()[2]); results.push({status:'observed',evidenceId:value.evidenceId,observation_id:observation.observation_id}); }
       catch (error) { var reason=CT_GAS.bound(error.message||error,240); CT_GAS_STATE.update('observer_processing',id,{payload:{identity:identity,state:'deferred',reason:reason}}); results.push({status:'deferred',evidenceId:value.evidenceId,reason:reason}); }
      count++;
    }
    return {status:'complete',processed:count,backlog:countFiles(inbox),results:results};
  }
    function exactKeys(value,allowed) { if(!value||typeof value!=='object'||Array.isArray(value))return false; var keys=Object.keys(value); if(keys.length!==allowed.length)return false; for(var i=0;i<keys.length;i++)if(allowed.indexOf(keys[i])<0)return false; return true; }
    function safeSemanticText(value,max) { return typeof value==='string'&&value.length>0&&value.length<=max&&!/[\r\n\0]/.test(value); }
    function validSemanticEnvelope(value) { var sourceClasses=['operator-supplied','execution-reported','mechanically-verified','independently-reviewed','runtime-observed','provider-reported'], claimTypes=['objective','execution-summary','completion','failure','verification','review-finding','rework','outcome','residual-uncertainty','other'], lineage=value&&value.lineage, lineageFields=lineage&&Object.keys(lineage).indexOf('sourceSessionId')>=0?['physicalExecutionId','workOrderId','sourceSessionId']:['physicalExecutionId','workOrderId']; if(!exactKeys(value,['schema','version','envelopeId','lineage','sources','claims','contentHash'])||value.schema!=='celestan-semantic-evidence-envelope-v1'||value.version!==1||!/^sem_[a-f0-9]{32}$/.test(String(value.envelopeId||''))||!exactKeys(lineage,lineageFields)||!safeSemanticText(lineage.physicalExecutionId,160)||!safeSemanticText(lineage.workOrderId,160)||lineage.sourceSessionId!=null&&!safeSemanticText(lineage.sourceSessionId,160)||!Array.isArray(value.sources)||!value.sources.length||value.sources.length>100||!Array.isArray(value.claims)||!value.claims.length||value.claims.length>50||JSON.stringify(value).length>65536)return false; var ids={}, used={}, claimIds={}; for(var i=0;i<value.sources.length;i++){var source=value.sources[i]; if(!exactKeys(source,['sourceId','sourceClass','reference','sha256','sourceExecutionId'])||!safeSemanticText(source.sourceId,160)||ids[source.sourceId]||sourceClasses.indexOf(source.sourceClass)<0||!safeSemanticText(source.reference,500)||source.sha256!==null&&!/^[a-f0-9]{64}$/.test(String(source.sha256))||source.sourceExecutionId!==null&&!safeSemanticText(source.sourceExecutionId,160)||source.sourceClass==='mechanically-verified'&&!source.sha256||source.sourceClass==='independently-reviewed'&&(!source.sourceExecutionId||source.sourceExecutionId===lineage.physicalExecutionId))return false; ids[source.sourceId]=true;} for(var j=0;j<value.claims.length;j++){var claim=value.claims[j]; if(!exactKeys(claim,['claimId','claimType','statement','supportSourceIds'])||!safeSemanticText(claim.claimId,160)||claimIds[claim.claimId]||claimTypes.indexOf(claim.claimType)<0||!safeSemanticText(claim.statement,1000)||!Array.isArray(claim.supportSourceIds)||!claim.supportSourceIds.length||claim.supportSourceIds.length>20)return false; claimIds[claim.claimId]=true; var local={}; for(var k=0;k<claim.supportSourceIds.length;k++){var sourceId=claim.supportSourceIds[k]; if(!safeSemanticText(sourceId,160)||!ids[sourceId]||local[sourceId])return false; local[sourceId]=true; used[sourceId]=true;}} if(Object.keys(used).length!==Object.keys(ids).length)return false; var body={schema:value.schema,version:value.version,lineage:lineage,sources:value.sources,claims:value.claims}, hash=digest(JSON.stringify(body)); return /^[a-f0-9]{64}$/.test(String(value.contentHash||''))&&hash===value.contentHash&&value.envelopeId==='sem_'+hash.slice(0,32); }
    function validTransportSemanticEnvelope(value) { if(!value||typeof value!=='object')return false; var lineage={physicalExecutionId:value.lineage&&value.lineage.physicalExecutionId,workOrderId:value.lineage&&value.lineage.workOrderId}; if(value.lineage&&value.lineage.sourceSessionId!=null)lineage.sourceSessionId=value.lineage.sourceSessionId; var normalized={schema:value.schema,version:value.version,envelopeId:value.envelopeId,lineage:lineage,sources:Array.isArray(value.sources)?value.sources.map(function(source){return {sourceId:source.sourceId,sourceClass:source.sourceClass,reference:source.reference,sha256:source.sha256,sourceExecutionId:source.sourceExecutionId};}):value.sources,claims:Array.isArray(value.claims)?value.claims.map(function(claim){return {claimId:claim.claimId,claimType:claim.claimType,statement:claim.statement,supportSourceIds:claim.supportSourceIds};}):value.claims,contentHash:value.contentHash}; return validSemanticEnvelope(normalized); }
    function richRecovery(value) { var f=value&&value.evidenceFidelity||{}; return f.mode==='rich'||f.sourceView==='ephemeral-unsanitized-rich-extraction'||f.sourceView==='rich-structural-extraction'||f.derivedTextPersisted===true; }
    function sanitizedHistorical(value) { var f=value&&value.evidenceFidelity||{}; return value&&value.substrate==='opencode-local-historical'&&f.mode==='sanitized'&&f.sourceView==='sanitized-structural'&&f.semanticEligibility==='structural-only'&&f.rawSourceDocumentPersisted===false&&f.derivedTextPersisted===false; }
    function semanticEligibility(value) { if(richRecovery(value))return {eligible:false,reason:'rich extraction is recovery-only'}; if(value&&value.substrate==='opencode-local-historical'&&!sanitizedHistorical(value))return {eligible:false,reason:'historical structural fidelity is not validated sanitized evidence'}; if(!validTransportSemanticEnvelope(value&&value.semanticEvidenceEnvelope))return {eligible:false,reason:'validated claim envelope is unavailable'}; return {eligible:true,reason:'validated claim envelope joined to eligible structure'}; }
    function validate(value,text) { if (!value||value.schema!=='celestan-execution-evidence-v1'||value.version!==1||!value.evidenceId||(!value.physicalExecutionId && !(value.substrate==='opencode-local-historical' && value.provenance && value.provenance.sourceSessionId))||!value.contentHash) throw new Error('unsupported evidence schema'); var copy={}; Object.keys(value).forEach(function(k){if(k!=='contentHash')copy[k]=value[k];}); if (digest(CT_GAS.json(copy))!==value.contentHash) throw new Error('evidence hash mismatch'); if (text.length>CT_GAS.MAX_EVIDENCE_BYTES) throw new Error('evidence exceeds bound'); }
   function appendObservation(value,semantic) { var folder=CT_GAS_EVIDENCE.folders()[2], name='observation-'+value.evidenceId+'-'+value.contentHash, old=folder.getFilesByName(name); if(old.hasNext())return {observation_id:old.next().getId()}; var file=folder.createFile(name,CT_GAS.bound(CT_GAS.json({schema:'celestan-semantic-observation-v1',evidenceId:value.evidenceId,physicalExecutionId:value.physicalExecutionId,observation:semantic,provenance:{evidenceId:value.evidenceId,hash:value.contentHash}}),CT_GAS.MAX_EVIDENCE_BYTES),MimeType.PLAIN_TEXT); return {observation_id:file.getId()}; }
  function quarantine(file,error) { var folder=CT_GAS_EVIDENCE.folders()[3]; file.moveTo(folder); CT_GAS_STATE.create('observer_processing',{id:CT_GAS.id('quarantine',file.getId()),kind:'processing',payload:{file_id:file.getId(),state:'quarantined',reason:CT_GAS.bound(error.message||error,240)}}); }
  function countFiles(folder) { var n=0,it=folder.getFiles(); while(it.hasNext()){it.next();n++;} return n; }
  function infer(value,clock) { var eligibility=semanticEligibility(value); if(!eligibility.eligible)throw new Error(eligibility.reason); var props=PropertiesService.getScriptProperties(), model=props.getProperty('CT_GAS_OBSERVER_MODEL')||props.getProperty('CT_GAS_PROOF_MODEL'); if(!model)throw new Error('Observer model is not configured'); var result=CT_GAS_AGENT.execute({model:model,verify_price:true,maxTurns:1,maxTokens:1024,role:'observer',task_purpose:'semantic evidence observation',execution_id:'observer-'+value.evidenceId,physical_execution_id:'observer-'+value.evidenceId,work_order_id:value.workOrderId||'evidence-observation',clock:clock,requiredMs:CT_GAS.OPERATION_BUDGETS.model,messages:[{role:'user',content:'Interpret only the bounded claims in this semantic evidence envelope. Return only JSON matching celestan-semantic-observation-v1. Do not infer from structural telemetry, invent facts, or expose secrets. Preserve source classification and cite envelope claim IDs. Evidence:\n'+CT_GAS.bound(CT_GAS.json(value.semanticEvidenceEnvelope),12000)}]}); if(result.status!=='complete')throw new Error('semantic inference '+result.status+' '+String(result.failure_category||result.reason||'unclassified')); var text=String(result.output||'').replace(/^```json\s*/,'').replace(/\s*```$/,''); var start=text.indexOf('{'),end=text.lastIndexOf('}'); if(start<0||end<start)throw new Error('semantic inference returned no JSON object'); return JSON.parse(text.slice(start,end+1)); }
  function digest(text) { return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,text,Utilities.Charset.UTF_8).map(function(b){return ('0'+(b<0?b+256:b).toString(16)).slice(-2);}).join(''); }
  function classifyLegacyArtifact(kind,row) { row=row||{}; var allowed=['execution_id','physical_execution_id','work_order_id','wake_id','continuation_id','handoff_id','checkpoint_digest','repository_digest','provider','model','operation','failure_category','status','state','lifecycle','revision','created_at','updated_at','started_at','finished_at','retry_count','attempt','duration_ms'], projection={}; allowed.forEach(function(key){var value=row[key]; if(value===null||typeof value==='boolean'||typeof value==='number'&&isFinite(value)||typeof value==='string'&&value.length<=500&&!/[\r\n\0]/.test(value))projection[key]=value;}); var sourceHash=digest(CT_GAS.json(row)), projectionHash=digest(CT_GAS.json(projection)); return {schema:'celestan-legacy-artifact-classification-v1',artifactId:CT_GAS.id('legacy-artifact',String(kind)+'|'+sourceHash),sourceKind:String(kind).slice(0,120),sourceHash:sourceHash,structuralProjection:projection,structuralProjectionHash:projectionHash,immutability:'content-addressed-snapshot',structuralUsability:'eligible',semanticEligibility:'ineligible',reason:'legacy-gas-reasoning-artifact'}; }
  function persistLegacyClassification(kind,row) { var value=classifyLegacyArtifact(kind,row), prior=CT_GAS_STATE.get('observer_processing',value.artifactId); if(prior&&prior.payload&&prior.payload.sourceHash!==value.sourceHash)throw new Error('legacy artifact classification conflict'); if(!prior)CT_GAS_STATE.create('observer_processing',{id:value.artifactId,kind:'legacy-classification',payload:value}); return value; }
  function pass(d) { d=d||{}; if (d.observer_active) return {status:'skipped',reason:'observer-recursion'}; var started=Date.now(), clock=d.clock; if (!clock) throw new Error('active clock is required for observer'); return CT_GAS.runGuard(clock,'observer-pass',CT_GAS.OPERATION_BUDGETS.observer,function () { persistLegacyClassification('observer-observed',d); var digest=CT_GAS.id('observer-digest',{execution_id:d.execution_id,work_order_id:d.work_order_id,wake_id:d.wake_id,continuation_id:d.continuation_id,evidence:d.evidence}); if (CT_GAS_STATE.observerObserved(d.execution_id,d.work_order_id,d.continuation_id,digest)) return {status:'observed',digest:digest,duplicate:true}; CT_GAS_STATE.event('observer_pending',{execution_id:d.execution_id,physical_execution_id:d.physical_execution_id,work_order_id:d.work_order_id,wake_id:d.wake_id,continuation_id:d.continuation_id,operation:'observer',digest:digest,lifecycle:'pending'}); if (!clock.canStart(CT_GAS.OPERATION_BUDGETS.observer)) return {status:'preempted',reason:'observer-checkpoint'}; CT_GAS_STATE.event('observer_observed',{execution_id:d.execution_id,physical_execution_id:d.physical_execution_id,work_order_id:d.work_order_id,wake_id:d.wake_id,continuation_id:d.continuation_id,operation:'observer',digest:digest,lifecycle:'observed'}); if (!clock.canStart(0)) return {status:'preempted',reason:'observer-post-operation'}; return {status:'observed',digest:digest,latency_ms:Date.now()-started}; }); }
  return {pass:pass,consume:consume,infer:infer,classifyLegacyArtifact:classifyLegacyArtifact,persistLegacyClassification:persistLegacyClassification,validSemanticEnvelope:validTransportSemanticEnvelope,semanticEligibility:semanticEligibility};
}());
function observePendingEvidence(clock) { return CT_GAS_OBSERVER.consume({clock:clock,limit:3,analyzer:function(value){return CT_GAS_OBSERVER.infer(value,clock);}}); }
